### PR TITLE
Add Litestar integration

### LINKED ISSUE #3081: Missing `starlite` docs
`starlite` integration was added in https://github.com/strawberry-graphql/strawberry/pull/2391 in which docs were added.

The doc file does exist - https://github.com/strawberry-graphql/strawberry/blob/main/docs/integrations/starlite.md

...but on the website there is no mention of it under Integrations:

image

...and searching for `starlite` in the docs also brings up no results.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3081">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3081/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by gazorby**
Add support for [Litestar](https://litestar.dev/).

## Description

This adds a _new_ integration and does not replace the Starlite one. It adds a bunch of duplicated code but allows a smoother transition from Starlite to Litestar.

We may decide to keep both for some time and consider dropping Starlite later on.

Usage is pretty much identical as for Starlite :

```python
import strawberry
from litestar import Request, Litestar
from strawberry.litestar import make_graphql_controller, BaseContext
from strawberry.types.info import Info

@strawberry.type
class Query:
    @strawberry.field
    def hello(self, info: Info[object, None]) -> str:
        return info.context["custom"]


class CustomContext(BaseContext):
    session: AsyncSession


async def custom_context_getter():
    async with async_session_maker() as session:
        yield CustomContext(session=session)


schema = strawberry.Schema(Query)

GraphQLController = make_graphql_controller(
    schema,
    path="/graphql",
    context_getter=custom_context_getter
)

app = Litestar(route_handlers=[GraphQLController])
```

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* Closes #3118 
* Closes #3081 
* Closes #3082 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

This release adds support for [litestar](https://litestar.dev/).

```python
import strawberry
from litestar import Request, Litestar
from strawberry.litestar import make_graphql_controller
from strawberry.types.info import Info


def custom_context_getter(request: Request):
    return {"custom": "context"}


@strawberry.type
class Query:
    @strawberry.field
    def hello(self, info: Info[object, None]) -> str:
        return info.context["custom"]


schema = strawberry.Schema(Query)


GraphQLController = make_graphql_controller(
    schema,
    path="/graphql",
    context_getter=custom_context_getter,
)

app = Litestar(
    route_handlers=[GraphQLController],
)
```



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Matthieu MN for the PR 👏

Get it here 👉 https://beta.strawberry.rocks/release/(next)
```

**Comment by gazorby** [comment]
Documentation is missing, and the one for Starlite does not show up in the index

**Comment by gazorby** [comment]
Documentation added, should ready for review

**Comment by betaboon** [comment]
is there anything we can do to help out getting this in?

**Comment by patrick91** [comment]
@gazorby thank you for this and sorry for the delay, I'll review and merge soon 😊

**Review by patrick91 — APPROVED** [review]
Awesome! I think we'll have to deprecate starlite, but we can do that in another PR 😊

**Pull request merged**
