### PR TITLE
Fix strawberry.directives typo in CHANGELOG (#161)

### LINKED ISSUE #161: Expose DirectiveLocation from strawberry.directives
Our changelog has this example for directives:

```python
import strawberry
from strawberry.directives import DirectiveLocation

@strawberry.type
class Query:
    cake: str = "made_in_switzerland"

@strawberry.directive(
    locations=[DirectiveLocation.FIELD], description="Make string uppercase"
)
def uppercase(value: str, example: str):
    return value.upper()

schema = strawberry.Schema(query=Query, directives=[uppercase])
```

but we don't have `strawberry.directives` package :)

### PR DESCRIPTION
**Pull request by Erfaniaa**
Fix strawberry.directives typo in CHANGELOG (resolves #161)

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
Thanks @Erfaniaa! I'll merge this and skip the release process as this changes only the changelog :)

please send me an email with your address if you want a strawberry sticker :) I'm travelling right now, but I'll try to ship you one as soon as I can :)

**Comment by Erfaniaa** [comment]
Thank you @patrick91! May I send my information to your email?

**Comment by patrick91** [comment]
@Erfaniaa yes! It is on my GitHub profile :)

**Pull request merged**
