### PR TITLE
Add graphql_type parameter to `strawberry.field`

### LINKED ISSUE #2308: Duck typing / being allow to override the field types 🦆
I'm opening this issue to document how we can make it easier to override return types.

## Problem description

When using a framework like Django, you tend to directly return models in resolvers, for example:

```python
@strawberry.type
class Query:
    @strawberry.field
    def all_users(self) -> list[UserType]:
         return models.User.objects.all()
```

Assuming that `UserType` has a subset of models.User fields, this will work at runtime as we don't do a type check of the returned type[1].

Unfortunately this break type checking (mypy, pyright, etc) as the return type of `models.User.objects.all()` is `Queryset[models.User]` and the return type of `all_users` is `list[UserType]`.

## Ideas 

One way to work around this is the following:

```python
@strawberry.type
class Query:
    @strawberry.field
    def all_users(self) -> list[UserType]:
         return cast(list[UserType], models.User.objects.all())
```

---

@jkimbo suggested to allow doing something like this:

```python
@strawberry.type
class Query:
    @strawberry.field(field_type=list[UserType])
    def all_users(self) -> Queryset[models.User]:
        return models.User.objects.all()
```

and 

```python
@strawberry.type
class MyType:
  my_field: float = strawberry.field(field_type=str)

MyType(my_field=1.33) # this wouldn’t be a problem
```

[1] graphql-core has some type checks, but it is for scalars and nullability.

### PR DESCRIPTION
**Pull request by jkimbo**
## Description

This PR adds a new `graphql_type` parameter to `strawberry.field` that allows you to explicitly set the field type. This parameter will take preference over the resolver return type and the class field type.

For example:

```python
@strawberry.type
class Query:
    a: float = strawberry.field(graphql_type=str)
    b = strawberry.field(graphql_type=int)

    @strawberry.field(graphql_type=float)
    def c(self):
        return "3.4"

schema = strawberry.Schema(Query)

str(schema) == """
  type Query {
    a: String!
    b: Int!
    c: Float!
  }
"""
```

### Notes:

~~I'm open to alternative names to `field_type`. It doesn't look that great to have the duplication on `strawberry.field(field_type` but I didn't want to use just `type` since it's a built in function in Python.~~
Renamed to `graphql_type`.

### Implementation notes:

I noticed that we almost have this feature with the `type_annotation` parameter on `StrawberryField` so I just renamed it to `graphql_type` and exposed it in the decorator.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes #2308

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Jonathan Kim for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by patrick91** [comment]
I haven't seen the code yet, but I wonder about the name of the parameter, it might lead to some confusion, or not be clear that it is the GraphQL type. 

Maybe we should call it graphql_type? :)

**Comment by jkimbo** [comment]
> Maybe we should call it graphql_type? :)

Yep, like that name more.

**Comment by jkimbo** [comment]
@patrick91 updated. Also it would be helpful to get a pre-release of this so that I can check it against the Django integration.

**Comment by jkimbo** [comment]
This should land first: https://github.com/strawberry-graphql/strawberry/pull/2319

**Comment by patrick91** [comment]
Looks good! Do we need to update Strawberry Django when merging this?

**Review by patrick91 — APPROVED** [review]

**Comment by jkimbo** [comment]
> Looks good! Do we need to update Strawberry Django when merging this?

Based on my track record probably! Can you create a pre release?

**Comment by patrick91** [comment]
@jkimbo I forgot, we need a release file for the release bot to work 😊

**Comment by jkimbo** [comment]
> I forgot, we need a release file for the release bot to work 😊

@patrick91 that makes sense! I've added a release file now. Should probably update the docs as well.

**Comment by botberry** [comment]
# Pre-release
:wave:

Releasing commit [4305e718efb12e3e412c66e9bcc08f57b758c4b7] to PyPi as pre-release! :package:

**Comment by botberry** [comment]
# Pre-release
:wave:

Pre-release **0.141.0.dev.1668163238** [4305e718efb12e3e412c66e9bcc08f57b758c4b7] has been released on PyPi! :rocket:
You can try it by doing:

```shell
poetry add strawberry-graphql==0.141.0.dev.1668163238
```

**Comment by jkimbo** [comment]
Looks like I haven't broken anything in strawberry-django 🥳

**Pull request merged**
