### PR TITLE
Install litestart instead of starlite

### PR DESCRIPTION
**Pull request by patrick91**
We need to update the name of the integration too :'D

Also I'm surprised the import are still working. Not sure if we need to add any deprecation change for this 🤔

### CODE REVIEW

**Comment by botberry** [comment]
## Apollo Federation Subgraph Compatibility Results

<table>
<thead>
<tr><th>Federation 1 Support</th><th>Federation 2 Support</th></tr>
</thead>
<tbody>
<tr><td><table><tr><th><code>_service</code></th><td>🟢</td></tr><tr><th><code>@key (single)</code></th><td>🟢</td></tr><tr><th><code>@key (multi)</code></th><td>🟢</td></tr><tr><th><code>@key (composite)</code></th><td>🟢</td></tr><tr><th><code>repeatable @key</code></th><td>🟢</td></tr><tr><th><code>@requires</code></th><td>🟢</td></tr><tr><th><code>@provides</code></th><td>🟢</td></tr><tr><th><code>federated tracing</code></th><td>🔲</td></tr></table></td><td><table><tr><th><code>@link</code></th><td>🟢</td></tr><tr><th><code>@shareable</code></th><td>🟢</td></tr><tr><th><code>@tag</code></th><td>🟢</td></tr><tr><th><code>@override</code></th><td>🟢</td></tr><tr><th><code>@inaccessible</code></th><td>🟢</td></tr><tr><th><code>@composeDirective</code></th><td>🟢</td></tr><tr><th><code>@interfaceObject</code></th><td>🟢</td></tr></table></td></tr>
</tbody>
</table>

Learn more:
* [Apollo Federation Subgraph Specification](https://www.apollographql.com/docs/federation/subgraph-spec/)
* [Compatibility Tests](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/COMPATIBILITY.md)

**Comment by gazorby** [comment]
Hi @patrick91, I have a working integration with Litestar v2 locally so I can send a PR if you want ;)
Some changes I made to make v2 work may not be backward compatible, so maybe we can temporarily keep two separate integrations for Starlite/Litestar while marking Starlite as deprecated and removing it in a future release.

**Comment by patrick91** [comment]
> Hi @patrick91, I have a working integration with Litestar v2 locally so I can send a PR if you want ;)
> 
> Some changes I made to make v2 work may not be backward compatible, so maybe we can temporarily keep two separate integrations for Starlite/Litestar while marking Starlite as deprecated and removing it in a future release.

that would be amazing! happy to review the PR and merge it 😊 thank you! <3

**Comment by gazorby** [comment]
Hi @patrick91 ;)
I haven't found the time yet, will try to send a PR this week !

**Pull request closed without merging**
