### PR TITLE
Add sentinel value to match unset client input

### LINKED ISSUE #321: Use sentinel value for input parameters that aren't sent by the clients
When using input types with optional fields we cannot differentiate by fields that have sent as null and fields that haven't been sent at all.

So I think we should use a sentinel value that tells the field is unset, and also behaves as falsy:

```python
class _Unset:
    def __bool__(self): return False

UNSET = _Unset()

# this utility might be useful, so we don't have to use an internal representation
def is_unset(value: Any):
    return value is UNSET
```

then we can use this class when instantiating the input types for a resolver:)

### PR DESCRIPTION
**Pull request by Rwothoromo**
## Description

> When using input types with optional fields we cannot differentiate by fields that have sent as null and fields that haven't been sent at all.
I've added a sentinel value that tells that a field is unset.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* fixes #321 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by Rwothoromo** [comment]
> Awesome stuff, thanks for taking this!

My pleasure. Thanks for the unblocking too.

**Comment by patrick91** [comment]
I need to fix a test on PyCon's Italy website before merging this.

**Comment by patrick91** [comment]
all good now, I added a `__str__` to fix some issues on PyCon Italia 😊

**Comment by patrick91** [comment]
I need to figure out pre-commit

**Comment by Rwothoromo** [comment]
> all good now, I added a `__str__` to fix some issues on PyCon Italia 😊

Awesome!

**Pull request merged**
