### PR TITLE
remove stack_info from logging

### PR DESCRIPTION
**Pull request by finsterwalder**
## Description

stack_info (as described here: https://docs.python.org/3/library/logging.html#logging.Logger.debug) adds the stacktrace to the location where the logger.error call was done. That is not helpful when using strawberry, since it's always the same location, so it just adds clutter.

Since exec_info is properly passed to the logger, the actual location of the problem is available and that is what is interesting during logging.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* https://github.com/strawberry-graphql/strawberry/issues/2384

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @finsterwalder for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by bellini666 — APPROVED** [review]
I agree with this, LGTM :)

**Comment by ossareh** [comment]
Happy to defer on this one; literally so long since I last had to think about Python logging that I cannot the intent here.

**Comment by patrick91** [comment]
> Happy to defer on this one; literally so long since I last had to think about Python logging that I cannot the intent here.

thanks for double checking!

I'll try the PR in the next couple of days and see the actual difference 😊

**Review by patrick91 — APPROVED** [review]
Just checked this and it looks good! Thank you!

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
