### PR TITLE
Integrate websockets into the async base view

### PR DESCRIPTION
**Pull request by DoctorJohn**
## Description

This PR introduces adapter classes for WebSockets, similar to the adapter classes for HTTP requests. This allows us to share all common WebSocket logic between all integrations.

As a result, WebSockets now behave much more consistently between different integrations, which allows us to share all WebSocket tests between them.

I put much energy into keeping this a non-breaking change and keeping it as reviewable as possible. As a result, the Channels integration still looks as funny as before, i.e., its HTTP and WS handlers are still split. This deserves another look in a separate PR.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Summary by Sourcery

Integrate WebSocket adapter classes into the async base view to unify WebSocket logic across integrations, ensuring consistent behavior and simplifying maintenance. Remove redundant WebSocket handler implementations and update tests to reflect the new architecture.

New Features:
- Introduce adapter classes for WebSockets to unify and share common WebSocket logic across different integrations, enhancing consistency and maintainability.

Enhancements:
- Refactor WebSocket handling to use a shared base class, improving consistency and reducing duplication across HTTP integrations.

Tests:
- Add new tests to verify the behavior of WebSocket subprotocol handling, including scenarios for unsupported subprotocols and client preferences.

Chores:
- Remove obsolete WebSocket handler files and tests that are no longer needed due to the new unified WebSocket handling approach.

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Starting with this release, WebSocket logic now lives in the base class shared between all HTTP integrations.
This makes the behaviour of WebSockets much more consistent between integrations and easier to maintain.



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @NucleonJohn for the PR 👏

Get it here 👉 https://strawberry.rocks/release/(next)
```

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Starting with this release, WebSocket logic now lives in the base class shared between all HTTP integrations.
This makes the behaviour of WebSockets much more consistent between integrations and easier to maintain.



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @NucleonJohn for the PR 👏

Get it here 👉 https://strawberry.rocks/release/(next)
```

**Comment by patrick91** [comment]
This PR makes me so happy <3

**Comment by erikwrede** [comment]
@patrick91 wait until we get the incremental delivery going 🫢

**Review by patrick91 — APPROVED** [review]
Looks solid!

**Pull request merged**
