### PR TITLE
Update precommit and migrate some configuration to the pyproject.toml

### PR DESCRIPTION
**Pull request by patrick91**
Admin stuff :D

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by BryceBeagle** [comment]
What's up with 3rd-party libraries being grouped with built-in modules now?

**Comment by patrick91** [comment]
@BryceBeagle trying to figure out, looks like `seed-isort-config` has been deprecated and `known_third_party` doesn't work as before 🤔

**Comment by BryceBeagle** [comment]
Also, thoughts on moving the isort config to the pyproject.toml?

**Comment by patrick91** [comment]
> Also, thoughts on moving the isort config to the pyproject.toml?

didn't know it was possible! happy to move it as soon as I figure out what's wrong :D

**Comment by BryceBeagle** [comment]
Maybe it will "just work" from the toml :smirk:

**Review by BryceBeagle — APPROVED** [review]

**Pull request merged**
