### PR TITLE
Removed csrf_exempt from django views

### PR DESCRIPTION
**Pull request by Speedy1991**
I think it's not a good idea to disable security features by default. If one wants an csrf exempt, you can wrap your view in urls with this decorator.

E.g.:

```
from strawberry.django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path("graphql/", csrf_exempt(GraphQLView.as_view(), name='graphql'))
]
```

I didn't expect this exemp and the server could have been vulnerable to CSRF attacks by default.

## Description

Removed the decorators

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation. (maybe - not sure?)
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage) (tested in my own project with overwritten dispatch method)

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by Speedy1991** [comment]
Anything missing to get this merged?

friendly ping @patrick91

**Comment by patrick91** [comment]
> Anything missing to get this merged?
> 
> friendly ping @patrick91

I'll do a review this week, I want to check that:

1. the graphiql interface still works by default
2. we have a friend error


I think point 2 is quite important because we don't users to spend a lot of time debugging issue with CSRF tokens, especially if they are beginners. We might need to write docs for that. What do you think?

**Comment by jkimbo** [comment]
I don't think this is the right approach for a couple of reasons:

1. It's quite a disruptive change for current users because it will likely break current applications. Also it probably won't show up in tests because they usually don't test the http layer.

2. I think that defaulting to exempting the view from csrf checks is actually a good default for Strawberry because it matches how most people use graphql. I don't have any solid evidence for this but I would assume that most people use graphql in a single page application or mobile app that is not hosted by Django and so getting the csrf token is not trivial. 

---

I think a better solution would be to make csrf protection an option on the GraphQLView. It could be a required option so that people are forced to choose whether to opt in or out. That way it would be obvious at app startup rather than later at runtime. 

What do you think @Speedy1991 @patrick91 ?

**Comment by patrick91** [comment]
Uh, an option could be a better solution! 

I agree with all your points :)

**Comment by Speedy1991** [comment]
I'm still not 100% convinced. Because "it will likely break current applications" we will keep a potential security issue? At least we could add a warning about disabled CSRF

Anyway, I like the suggested "options" if it is a required arg/kwarg :)

**Comment by jkimbo** [comment]
@Speedy1991 yep I agree, a required option is the way forward IMO. Could you update this PR?

**Comment by BryceBeagle** [comment]
Could the option be not required, but default to the more secure approach?

**Comment by jkimbo** [comment]
> Could the option be not required, but default to the more secure approach?

I think we should require the option to be set first to avoid accidentally breaking things (it would break my application for example). We can then default to requiring csrf protection in the future.

**Comment by g-as** [comment]
My two cents to your point 2. @jkimbo 

It makes sense to disable CSRF checks for a _public_ API where third parties consume it. But for a _private_ API used by a single client (SPA), the cost of fetching the CSRF token (and keep the safety on) is low IMHO.

And +1 on your latest proposal!

**Comment by Speedy1991** [comment]
> ```python
> urlpatterns = [
>     path("graphql/", GraphQLView.as_view(schema=schema, csrf_protection=True)),
> ]
> ```

I dislike the idea to add an arg to `as_view` when `path("graphql/", csrf_exempt(GraphQLView.as_view(), name='graphql'))` does the same (like "do not reinvent the wheel")

And url capsulation is more the "django way" IMO

Maybe we can put it in the v1 release as breaking change?

However, I'm glad if this gets fixed in any way

**Comment by Speedy1991** [comment]
Rebased to current master

To prevent breaking changes i kept the classes "as is" but added a warning about the disabled csrf stuff

**Comment by paltman** [comment]
A simple work around is just to add the following to your project:

```python
from strawberry.django.views import GraphQLView


class ProtectedGraphQLView(GraphQLView):

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
```

Then use `ProtectedGraphQLView` in your `urls.py`.  This seems to override the `@method_decorator` on the `GraphQLView` base class.

**Comment by patrick91** [comment]
@bellini666 do you have opinions on this PR? 😊

**Comment by bellini666** [comment]
> @bellini666 do you have opinions on this PR? blush

I mostly agree with @jkimbo's points. I also don't have any evidence of that, but I have a strong feeling that most people using strawberry and/or DRF are not using csrf by default.

I'm not totally against this, but I would say that based on the fact that the minority of users would use CSRF for graphql APIs, and when someone wants to use it for such they probably know that they need to write some extra code in the client to get that and send it in a different way (e.g. in a header), it is probably better to have an example aimed at them at the docs with [paltman's suggestion](https://github.com/strawberry-graphql/strawberry/pull/1046#issuecomment-1086757715) to enable it.

**Comment by patrick91** [comment]
@bellini666 makes sense, I'll close this then!

**Comment by Arfey** [comment]
@bellini666 

if u have API which use cookie for authentication and some query can mutate user data then csrf is critical security issue. When I use `django.middleware.csrf.CsrfViewMiddleware` I expect that all my views are protected.

>I have a strong feeling that most people using strawberry and/or DRF are not using csrf by default.

I have a strong feeling that many people don't know they have this problem in the project and will be surprised 😅

@jkimbo good suggestion with `csrf_protection` parameter

**Pull request closed without merging**
