### PR TITLE
Fix deprecation warning in apollo extension.

### LINKED ISSUE #3409: `ApolloTracingExtension` raises deprecation warning.
## Describe the Bug
[`datetime.utcnow` is deprecated](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) as of Python 3.12.

```python
  .venv/lib/python3.12/site-packages/strawberry/extensions/tracing/apollo.py:89: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self.start_time = datetime.utcnow()

  /.venv/lib/python3.12/site-packages/strawberry/extensions/tracing/apollo.py:92: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self.end_time = datetime.utcnow()
```

## System Information
 - Strawberry version (if applicable): 0.220

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3409">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3409/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by coady**
## Description
Updates `datetime.now` in utc. Fixes #3409.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #3409

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Fix deprecation warning in apollo extension.



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to A. Coady for the PR 👏

Get it here 👉 https://beta.strawberry.rocks/release/(next)
```

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Fix deprecation warning in apollo extension.



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to A. Coady for the PR 👏

Get it here 👉 https://beta.strawberry.rocks/release/(next)
```

**Review by DoctorJohn — APPROVED** [review]
Thanks for the PR @coady! Straight forward change I recently applied to some personal projects myself. Not sure why the docs were reformatted, but our linter seems to be happy so thats fine.

**Review by patrick91 — APPROVED** [review]
Thank you! And sorry for taking so long to merge this 😊

**Pull request merged**
