### PR TITLE
Add extra for starlite

### LINKED ISSUE #2663: Make starlite optional
As of `0.168.0`, `starlite` becomes a mandatory dependency, which seems like either an oversight (relative to other integrations) or a misconfiguration.

See the content of https://pypi.org/pypi/strawberry-graphql/json:
```JSON
        "requires_dist": [
            "graphql-core (>=3.2.0,<3.3.0)",
            "typing_extensions (>=3.7.4,<5.0.0)",
            "python-dateutil (>=2.7.0,<3.0.0)",
            "starlette (>=0.18.0) ; extra == \"asgi\" or extra == \"debug-server\"",
            "click (>=7.0,<9.0) ; extra == \"debug-server\" or extra == \"cli\"",
            "pygments (>=2.3,<3.0) ; extra == \"debug-server\" or extra == \"cli\"",
            "uvicorn (>=0.11.6,<0.22.0) ; extra == \"debug-server\"",
            "Django (>=3.2) ; extra == \"django\"",
            "asgiref (>=3.2,<4.0) ; extra == \"django\" or extra == \"channels\"",
            "flask (>=1.1) ; extra == \"flask\"",
            "opentelemetry-api (<2) ; extra == \"opentelemetry\"",
            "opentelemetry-sdk (<2) ; extra == \"opentelemetry\"",
            "chalice (>=1.22,<2.0) ; extra == \"chalice\"",
            "pydantic (<2) ; extra == \"pydantic\"",
            "python-multipart (>=0.0.5,<0.0.7) ; extra == \"asgi\" or extra == \"debug-server\" or extra == \"fastapi\"",
            "sanic (>=20.12.2) ; extra == \"sanic\"",
            "aiohttp (>=3.7.4.post0,<4.0.0) ; extra == \"aiohttp\"",
            "fastapi (>=0.65.2) ; extra == \"fastapi\"",
            "starlite (>=1.48.0) ; python_version >= \"3.8\" and python_version < \"4.0\"",
            "channels (>=3.0.5) ; extra == \"channels\"",
            "backports.cached-property (>=1.0.2,<2.0.0) ; python_version < \"3.8\"",
            "astunparse (>=1.6.3,<2.0.0) ; python_version < \"3.9\"",
            "libcst (>=0.4.7) ; extra == \"debug\" or extra == \"debug-server\" or extra == \"cli\"",
            "rich (>=12.0.0) ; extra == \"debug\" or extra == \"debug-server\" or extra == \"cli\""
        ],
```
`starlite` is not linked to an extra identifier.

See also strawberry in a `poetry.lock`:
```TOML
[[package]]
name = "strawberry-graphql"
version = "0.168.0"
description = "A library for creating GraphQL APIs"
category = "main"
optional = false
python-versions = ">=3.7,<4.0"
files = [
    {file = "strawberry_graphql-0.168.0-py3-none-any.whl", hash = "sha256:6beaaad859edda74ffb63faafb9bc5b0ae88b4a7cf3d918bb858feb21b4428fa"},
    {file = "strawberry_graphql-0.168.0.tar.gz", hash = "sha256:6a97b6dcc87fdd4b68eed6503fab457979d2fa030f4c05ab6ca44d069b338b9c"},
]

[package.dependencies]
graphql-core = ">=3.2.0,<3.3.0"
libcst = {version = ">=0.4.7", optional = true, markers = "extra == \"debug\" or extra == \"debug-server\" or extra == \"cli\""}
python-dateutil = ">=2.7.0,<3.0.0"
rich = {version = ">=12.0.0", optional = true, markers = "extra == \"debug\" or extra == \"debug-server\" or extra == \"cli\""}
starlite = {version = ">=1.48.0", markers = "python_version >= \"3.8\" and python_version < \"4.0\""}
typing_extensions = ">=3.7.4,<5.0.0"

[package.extras]
aiohttp = ["aiohttp (>=3.7.4.post0,<4.0.0)"]
asgi = ["python-multipart (>=0.0.5,<0.0.7)", "starlette (>=0.18.0)"]
chalice = ["chalice (>=1.22,<2.0)"]
channels = ["asgiref (>=3.2,<4.0)", "channels (>=3.0.5)"]
cli = ["click (>=7.0,<9.0)", "libcst (>=0.4.7)", "pygments (>=2.3,<3.0)", "rich (>=12.0.0)"]
debug = ["libcst (>=0.4.7)", "rich (>=12.0.0)"]
debug-server = ["click (>=7.0,<9.0)", "libcst (>=0.4.7)", "pygments (>=2.3,<3.0)", "python-multipart (>=0.0.5,<0.0.7)", "rich (>=12.0.0)", "starlette (>=0.18.0)", "uvicorn (>=0.11.6,<0.22.0)"]
django = ["Django (>=3.2)", "asgiref (>=3.2,<4.0)"]
fastapi = ["fastapi (>=0.65.2)", "python-multipart (>=0.0.5,<0.0.7)"]
flask = ["flask (>=1.1)"]
opentelemetry = ["opentelemetry-api (<2)", "opentelemetry-sdk (<2)"]
pydantic = ["pydantic (<2)"]
sanic = ["sanic (>=20.12.2)"]
```

Also, `starlite` package already knows its compatibility with python, having it specified in `strawberry` feels redundant (`^3.8`). I'm only saying this because we already had this conversation with `django`'s python versions, and ended up only specifying a lower bound (https://github.com/strawberry-graphql/strawberry/pull/1687).

### PR DESCRIPTION
**Pull request by patrick91**
Closes #2663

@g-as does this look good to you?

### CODE REVIEW

**Comment by botberry** [comment]
## Apollo Federation Subgraph Compatibility Results

<table>
<thead>
<tr><th>Federation 1 Support</th><th>Federation 2 Support</th></tr>
</thead>
<tbody>
<tr><td><table><tr><th><code>_service</code></th><td>🟢</td></tr><tr><th><code>@key (single)</code></th><td>🟢</td></tr><tr><th><code>@key (multi)</code></th><td>🟢</td></tr><tr><th><code>@key (composite)</code></th><td>🟢</td></tr><tr><th><code>repeatable @key</code></th><td>🟢</td></tr><tr><th><code>@requires</code></th><td>🟢</td></tr><tr><th><code>@provides</code></th><td>🟢</td></tr><tr><th><code>federated tracing</code></th><td>🔲</td></tr></table></td><td><table><tr><th><code>@link</code></th><td>🟢</td></tr><tr><th><code>@shareable</code></th><td>🟢</td></tr><tr><th><code>@tag</code></th><td>🟢</td></tr><tr><th><code>@override</code></th><td>🟢</td></tr><tr><th><code>@inaccessible</code></th><td>🟢</td></tr><tr><th><code>@composeDirective</code></th><td>🟢</td></tr><tr><th><code>@interfaceObject</code></th><td>🟢</td></tr></table></td></tr>
</tbody>
</table>

Learn more:
* [Apollo Federation Subgraph Specification](https://www.apollographql.com/docs/federation/subgraph-spec/)
* [Compatibility Tests](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/COMPATIBILITY.md)

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

This releases adds a new `extra` group for Starlite, preventing it from being
installed by default.


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @patrick91 for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by patrick91** [comment]
It fails because the lockfile has also some updates for sanic, will revert them

**Comment by g-as** [comment]
LGTM

**Pull request merged**
