### PR TITLE
Edit wrong example of source code in Doc

### PR DESCRIPTION
**Pull request by pinkrespect**
When `@strawberry.type` is not writed on `class Mutation`, then It isn't work.

## Description

I tried Mutation as follow example source code in Doc, there was a error in example source code.
I saw unit test in here and change it right way.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by pinkrespect** [comment]
Anyone please help my pull request? I'm new to contributing open source project.

**Comment by BryceBeagle** [comment]
Hi @pinkrespect, thanks for the PR!

Good catch on the example in the docs. Because the change is a minor one to just the docs, don't worry about the bot asking for a changelog entry :slightly_smiling_face:

**Review by patrick91 — APPROVED** [review]
Good catch! Thanks for the PR! I'll merge it now 😊 

Can you fill this form for the Strawberry sticker? https://forms.gle/TW5qetvCe8Kn6uG57

**Pull request merged**
