### PR TITLE
Add support for batching

### LINKED ISSUE #1383: support batched queries
It would be awesome if strawberry would support [batched queries](https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/)

I already spend some time into this and this is my very first working example
The error handling is garbage but I hope you get the idea:

```
# strawberry/http.py
def process_result(result: ExecutionResult) -> Union[GraphQLHTTPResponse, List[GraphQLHTTPResponse]]:
    if isinstance(result, list):
        data: List[GraphQLHTTPResponse] = {"data": [r.data for r in result]}
        data["errors"] = [[format_graphql_error(err) for err in (getattr(r, 'errors', []) or [])] for r in result]
        if not data["errors"]:
            del data["errors"]
        data["extensions"] = [getattr(r, 'extensions', None) for r in result]
        if not data["extensions"]:
            del data["extensions"]
    else:
        data: GraphQLHTTPResponse = {"data": result.data}
        if result.errors:
            data["errors"] = [format_graphql_error(err) for err in result.errors]
        if result.extensions:
            data["extensions"] = result.extensions

    return data

def parse_request_data(data: Union[Dict, List[Dict]]) -> Union[GraphQLRequestData, List[GraphQLRequestData]]:
    if isinstance(data, list):
        if not all([ d.get('query', None) for d in data]):
            raise MissingQueryError()
        results = [
            GraphQLRequestData(query=d["query"], variables=d.get("variables"), operation_name=d.get("operationName"))
            for d in data
        ]
        return results

    if "query" not in data:
        raise MissingQueryError()

    result = GraphQLRequestData(
        query=data["query"],
        variables=data.get("variables"),
        operation_name=data.get("operationName"),
    )

    return result
```

```
# strawberry/django.views.py
if isinstance(request_data, list):
    result = [self.schema.execute_sync(
        rd.query,
        root_value=self.get_root_value(request),
        variable_values=rd.variables,
        context_value=context,
        operation_name=rd.operation_name,
    ) for rd in request_data]

else:
    result = self.schema.execute_sync(
        request_data.query,
        root_value=self.get_root_value(request),
        variable_values=request_data.variables,
        context_value=context,
        operation_name=request_data.operation_name,
    )
```

### PR DESCRIPTION
**Pull request by patrick91**
This PR adds support for batching. I want to make sure all the views get this :)

# TODO:

- [ ] Consolidate all the views (this can be done in another PR if I don't manage to have enough time)
- [ ] Allow to disable batching
- [ ] Support of async (with gather)

Closes #1383

### CODE REVIEW

**Comment by justuswilhelm** [comment]
This looks good. Looking forward to seeing this get merged.

**Comment by patrick91** [comment]
hi @justuswilhelm! that's good to know, do you need this for django or other frameworks? 😊

**Comment by justuswilhelm** [comment]
> hi @justuswilhelm! that's good to know, do you need this for django or other frameworks? 😊

Thanks for your fast response. Yes, I am using strawberry in django together with apollo in the frontend

**Comment by camflan** [comment]
@patrick91 I'd love to get this merged. Is there anything I can help with?

**Comment by patrick91** [comment]
@camflan I'll try to work on this in the next few weeks, I'm a bit busy and don't have a lot of free time :D 

Good to know there's people that need this 😊

**Comment by camflan** [comment]
> @camflan I'll try to work on this in the next few weeks, I'm a bit busy and don't have a lot of free time :D
> 
> Good to know there's people that need this 😊

Understood! We've started an initiative to get off graphene and this will be one of our blockers for rolling out to clients. If there's anything I can do to help please let me know

**Comment by patrick91** [comment]
@camflan thanks for offering! Please don't hesitate to ping me in discord if I forget :)

What integration are you using? :)

**Comment by patrick91** [comment]
@camflan I'll think about how we can enable this feature using schema extensions, if I don't find a good solution I'll keep working on this PR

**Comment by patrick91** [comment]
@camflan I'm working on refactoring the HTTP view layer before adding this. Shouldn't take too long 😊

**Comment by camflan** [comment]
> @camflan I'm working on refactoring the HTTP view layer before adding this. Shouldn't take too long 😊

Famous last words 🙈 😅

thanks for the update!

**Comment by patrick91** [comment]
@camflan that's been merged! I'll work on batching soon :)

Do you have any requirements? I need to think about security requirements for this, for now I think I'll add the following options:

1. Enable disable batching
2. Batching limit (max x operations)

but I wonder if we should put more :)

**Comment by camflan** [comment]
> @camflan that's been merged! I'll work on batching soon :)

Yay! 🥳 

> 
> Do you have any requirements? I need to think about security requirements for this, for now I think I'll add the following options:
> 
>     1. Enable disable batching
> 
>     2. Batching limit (max x operations)

I think both of those would cover what we need for now. Batching limit, rate limiting, etc could even be tackled later as a middleware instead of the core implementation, right?

**Comment by patrick91** [comment]
> I think both of those would cover what we need for now. Batching limit, rate limiting, etc could even be tackled later as a middleware instead of the core implementation, right?

depends on what you mean by middlewares, Strawberry extensions at the moment only work on a single operation.

But you'll be able to extend the GraphQL view/router to do additional validation. I think there's going to be a method called `run_batch` that will validate and execute the batching (and maybe a validate_batch method that can be used to change the validation if needed)

**Comment by patrick91** [comment]
closed in favour of #2698

**Pull request closed without merging**
