### PR TITLE
Improve error messages + add release.md requirements

### PR DESCRIPTION
**Pull request by sdobbelaere**
When requesting a non-existing cursor with pagination, the returned error was "An unknown error occurred.". Not a very transparent error message.  This PR addresses this issue.

If there other conditions under which the before_type and after_type would be incorrect, do please let me know.

Also, as the release.md file was a requirement for my last PR. I have taken the liberty to adding it to the README.md file to educate others.

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

- Improved error message when supplying in incorrect before or after argument with using relay and pagination.
- Add extra PR requirement in README.md



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to SD for the PR 👏

Get it here 👉 https://beta.strawberry.rocks/release/(next)
```

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

- Improved error message when supplying in incorrect before or after argument with using relay and pagination.
- Add extra PR requirement in README.md



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to SD for the PR 👏

Get it here 👉 https://beta.strawberry.rocks/release/(next)
```

**Review by bellini666 — APPROVED** [review]
LGTM :)

Would be nice to add a test for those if possible. Should be simples!

**Comment by sdobbelaere** [comment]
> LGTM :)
> 
> Would be nice to add a test for those if possible. Should be simples!

Sure, why not.  Not very familiar with pytest, but I added a couple of tests that fail the before and after.  The response did seem to yield a different content then in my Django environment.  But at least it's covered.

+
I changed the README again to refer to the CONTRIBUTE page.  Never realised it was there.

**Comment by sdobbelaere** [comment]
Hmm, that didn't take, the tests are skipping the TypeErrors.  I'll have to take another look on another day.

**Comment by sdobbelaere** [comment]
@bellini666 test are covering the change now.  Seems I had used a special query rather than the simple one.

**Comment by bellini666** [comment]
> @bellini666 test are covering the change now. Seems I had used a special query rather than the simple one.

Thanks! :)

**Pull request merged**
