### PR TITLE
Update GraphiQL UI screenshot in Getting started

### PR DESCRIPTION
**Pull request by asasvari**
Use the screenshots from version 0.195.3.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by asasvari** [comment]
> Hi 👋 You can find a preview of the docs here:
> 
> https://strawberry.rocks/docs/pr/2971/index
It looks strange, screenshots are not displayed:
image
@patrick91 any idea what went wrong here? I see browser fails to download https://strawberry.rocks/_next/image?url=.%2Fimages%2Findex-query-example.png&w=828&q=75

**Comment by patrick91** [comment]
@asasvari I'm taking a look, it's an issue on the website 😊

**Review by patrick91 — APPROVED** [review]
Thank you so much! 

I've fixed an issue on the site and this look perfect now 😊

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
