### PR TITLE
[mypy] updated 'extensions' arg type hint in Schema and execute to match ExtensionsRunner's arg

### PR DESCRIPTION
**Pull request by g-as**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by g-as** [comment]
Prevents this from happening:
```
schemas.py:40:9: error: List item 0 has incompatible type "ParserCache"; expected "Type[Extension]"  [list-item]
schemas.py:41:9: error: List item 1 has incompatible type "ValidationCache"; expected "Type[Extension]"  [list-item]
```

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Guillaume Andreu Sabater for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by DoctorJohn — APPROVED** [review]
LGTM 🎉 Thanks for the PR!

**Review by jkimbo — APPROVED** [review]
Thanks @g-as 

I've added a quick test and a Release file so that we can get this out as soon as possible

**Comment by g-as** [comment]
👍

**Pull request merged**
