### PR TITLE
[Discussion] Add kwarg to control fields visibility

### PR DESCRIPTION
**Pull request by Ambro17**
This PRs is incomplete and should serve as a complement of the discussion at #361 

For demonstration purposes i built a minimal schema with a hidden field that hides it from introspection and queries.
The behaviour of the visible function could be controlled by reading any relevant app config

## Example schema
```python
import strawberry


@strawberry.type
class Query:

    @strawberry.field
    def visible(self) -> str:
        return 'ABC'

    @strawberry.field(visible=lambda: False)
    def invisible(self) -> str:
        return 'ABC'


schema = strawberry.Schema(Query)
print('Schema SDL:\n', schema.as_str())
print('Introspection:\n', schema.execute_sync("""
    { 
        __schema {
            types {
                name
                fields {
                    name
                }
            }
        }
    }""")
)
print('Query Attempt:\n', schema.execute_sync('{invisible}').errors)
```
## Output
```
Schema SDL:
 type Query {
  visible: String!
}
Introspection:
 ExecutionResult(data={'__schema': {'types': [{'name': 'Query', 'fields': [{'name': 'visible'}]}, {'name': 'String', 'fields': None}, {'name': 'Boolean', 'fields': None}, {'name': '__Schema', 'fields': [{'name': 'description'}, {'name': 'types'}, {'name': 'queryType'}, {'name': 'mutationType'}, {'name': 'subscriptionType'}, {'name': 'directives'}]}, {'name': '__Type', 'fields': [{'name': 'kind'}, {'name': 'name'}, {'name': 'description'}, {'name': 'specifiedByUrl'}, {'name': 'fields'}, {'name': 'interfaces'}, {'name': 'possibleTypes'}, {'name': 'enumValues'}, {'name': 'inputFields'}, {'name': 'ofType'}]}, {'name': '__TypeKind', 'fields': None}, {'name': '__Field', 'fields': [{'name': 'name'}, {'name': 'description'}, {'name': 'args'}, {'name': 'type'}, {'name': 'isDeprecated'}, {'name': 'deprecationReason'}]}, {'name': '__InputValue', 'fields': [{'name': 'name'}, {'name': 'description'}, {'name': 'type'}, {'name': 'defaultValue'}]}, {'name': '__EnumValue', 'fields': [{'name': 'name'}, {'name': 'description'}, {'name': 'isDeprecated'}, {'name': 'deprecationReason'}]}, {'name': '__Directive', 'fields': [{'name': 'name'}, {'name': 'description'}, {'name': 'isRepeatable'}, {'name': 'locations'}, {'name': 'args'}]}, {'name': '__DirectiveLocation', 'fields': None}]}}, errors=None)
Query Attempt:
 [GraphQLError("Cannot query field 'invisible' on type 'Query'. Did you mean 'visible'?", locations=[SourceLocation(line=1, column=2)])]
```

## Alternative APIs
Pass filter function to Schema construction ([Reference](https://graphql-ruby.org/schema/limiting_visibility.html#filtering))
```python
def filter_types(gql_type) -> bool:
    pass

schema = strawberry.Schema(Query, except: filter_types)
```

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #361 

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
@Ambro17 interesting solution. I do like the API, but I wonder if we could do something where we can hide the fields based on the request?

I imagined this for public and private API, for example some API keys might have more fields :)

**Comment by Ambro17** [comment]
As we discussed on discord, it _is_ possible to hide fields based on context, but it requires changes on graphql-core
I leave the diff link here for anyone interested to peek at the required changes
https://github.com/graphql-python/graphql-core/compare/master...Ambro17:master

**Comment by Ambro17** [comment]
I think we could do something by adding some logic [here](https://github.com/strawberry-graphql/strawberry/blob/master/strawberry/schema/execute.py#L73-L74)
```
        with extensions_runner.validation():
            validation_errors = validate(schema, document)
```
If we added the context argument that is already available a few lines earlier we could send an error if any field is not visible for the given context.

What do you think about offering visibility as an extension? I'm not sure this was the intended use case when developed.. but it may work

**Comment by patrick91** [comment]
> What do you think about offering visibility as an extension? I'm not sure this was the intended use case when developed.. but it may work

Sorry I missed this message, so, for schema visibility to work we need these two things to happen:

1. the schema introspection doesn't return the hidden fields
2. the schema doesn't run any resolver related to the fields 

I think they can both be done via extensions, as you suggested, but I wonder if it is the best way, as we are basically changing the behaviour of the schema, instead of changing the schema itself. It would be ideal to change the way the schema is composed before even running anything related to the execution. 

I feel like the work that @BryceBeagle is doing in https://github.com/strawberry-graphql/strawberry/pull/489 will help with this

**Comment by Ambro17** [comment]
Hiding fields from the schema in build time is the easiest approach and it was what I first implemented, but i understood that you wanted to explore more granularity being able to hide them based on the context argument.
For that to work, the schema should have every field (perhaps wrapped in a custom object as the related pr proposes) and filter at execution time based on context.

In other words, if we want to dynamically hide fields, we would need a layer of abstraction on top of graphql core and perhaps the validation dance.

On the other hand, the second point may solve itself as soon as we decide on an approach on the first one.
I think it will never reach the resolver for a hidden field because a higher layer will be in charge of excluding it from a type fields

**Comment by patrick91** [comment]
> In other words, if we want to dynamically hide fields, we would need a layer of abstraction on top of graphql core and perhaps the validation dance.

yup, this is something we want to achieve with #489 :)

The idea is to run the schema building with the context of the request in mind, so we can allow developers to check for things like an API key :)

**Comment by Ambro17** [comment]
Oh i understand now, 
`strawberry.Schema(Query, Mutation, context={'api_scope': 'internal'})` would build schema `A` 
and
`strawberry.Schema(Query, Mutation, context={'api_scope': 'public'})` would build another schema.

Am i right?

In that case, the schema shown for each request would be the same?
Or should we update it/mask it once we receive a request?

**Comment by patrick91** [comment]
> Or should we update it/mask it once we receive a request?

I would do this, I think it might be the best option, I'll see if anyone has done something like this anywhere 😊

**Comment by Ambro17** [comment]
I think graphql ruby sets a good example, graphql java approach uses another approach using the visitor pattern that I didn't find really Pythonic but perhaps to disagree

**Comment by patrick91** [comment]
@Ambro17 would you be ok to close this and move it to a discussion? :)

**Comment by Ambro17** [comment]
No problem for me, I hadn't had the time to try passing the context to the query like ruby does not I won't have time on the near future so I think you can close it for staleness

**Comment by patrick91** [comment]
@Ambro17 perfect. I think this is a feature we might support in future, will let you know!

**Pull request closed without merging**
