### PR TITLE
Update dataloaders.md

### PR DESCRIPTION
**Pull request by mecampbellsoup**
Fix typo

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Review by patrick91 — APPROVED** [review]
Good spot! Thanks for taking time to fix the docs 😊

Would you be ok in adding a small RELEASE.md file? This will issue a new release, but also update the site (we only update the documentation on new releases).

It's not a big deal, we can also wait until we merge a new PR 😊

In any case thanks again for this! If you want I'll send you a sticker: https://forms.gle/9YxbHGXZGoymyzhSA

We also have a discord server if you want to chat about strawberry 😊 https://strawberry.rocks/discord

**Comment by mecampbellsoup** [comment]
> Would you be ok in adding a small RELEASE.md file?

Sure, happily!

**Comment by patrick91** [comment]
Thanks @mecampbellsoup!

**Pull request merged**
