### PR TITLE
Update poetry.lock

### PR DESCRIPTION
**Pull request by ulgens**
## Description

Update `poetry.lock` file.

`poetry.lock` file had outdated dependencies and it was creating (potential) clutter for other PRs, like https://github.com/strawberry-graphql/strawberry/pull/625 . I'm not sure why dependabot is not handling this.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* None

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
Thanks for this! Do you think we can add a CI check for the lock file? Might be useful :)

**Comment by ulgens** [comment]
@patrick91 As i know, Dependabot -kinda- is that CI check :slightly_smiling_face: I'm not sure why it didn't work here. I tried to check the config but config file doesn't live in the repo.

**Comment by patrick91** [comment]
This is the current config: 
image

**Comment by ulgens** [comment]
@patrick91 Thanks a lot. With that config, it doesn't check lock file content. If you remove that one tick from filters, it should go back to normal.

**Pull request merged**
