### PR TITLE
add option for reloader in strawberry server cli

### PR DESCRIPTION
**Pull request by peach-lasagna**
## Description
I am facing the problem that strawberry is preventing me from opening graphiql because someone is editing the file all the time. But nobody touches him ...
изображение

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by DoctorJohn** [comment]
@peach-lasagna would you still benefit from a CLI parameter like this? As far as I remember (from Discord) the underlying problem has been resolved. If so we could either close this PR or proceed reviewing it.

**Comment by peach-lasagna** [comment]
@DoctorJohn I think this feature is better to implemen

**Comment by DoctorJohn** [comment]
I this case I would prefer making it a `--no-reload` option, so that we still get a nice developer experience out of the box 😊

**Comment by patrick91** [comment]
@peach-lasagna I'll close this as we changed the implementation of the reloader, so hopefully it works better now!

**Pull request closed without merging**
