### PR TITLE
Move tests around

### PR DESCRIPTION
**Pull request by patrick91**
This partially reverts https://github.com/strawberry-graphql/strawberry/pull/2901

Ideal fix should re-revert the code, I just wanted to isolate the cause :)

I also took the opportunity to move a test from the wrong folder 😊

### CODE REVIEW

**Comment by patrick91** [comment]
@skilkis do you see anything that might have caused this regression? 😊

**Comment by bellini666** [comment]
@patrick91 @skilkis btw, running strawberry-graphql-django's testsuite with 0.192.2 broke 10 tests in there. On 0.192.1 they are fine:

```
FAILED tests/mutations/test_relationship.py::test_update_one_to_many - assert not [GraphQLError("Field 'FruitPartialInput.name' of required type 'String!' was not provided.", locations=[SourceLocation(line=1, column=39)])]
FAILED tests/mutations/test_relationship.py::test_update_many_to_one - assert not [GraphQLError("Field 'ColorPartialInput.name' of required type 'String!' was not provided.", locations=[SourceLocation(line=1, column=39)])]
FAILED tests/mutations/test_relationship.py::test_update_many_to_many - assert not [GraphQLError("Field 'FruitTypePartialInput.name' of required type 'String!' was not provided.", locations=[SourceLocation(line=1, column=42)])]
FAILED tests/fields/test_input.py::test_partial_input_type_inheritance - AssertionError: assert [('name', <class 'str'>)] == [('name', <strawberry.type.StrawberryOptional object at 0x7fd2c5dfc6d0>)]
FAILED tests/fields/test_types.py::test_inherit_partial_input - AssertionError: assert [('char', <class 'str'>, False), ('one_to_one', <strawberry.type.StrawberryOptional object at 0x7fd2c5dc3610>, True)] == [('char', <strawberry.type.StrawberryOptional object at 0x7fd2c5dc3650>, True), ('one_to_...
FAILED tests/filters/test_types.py::test_inherit[input] - AssertionError: assert [('id', <strawberry.type.StrawberryOptional object at 0x7fd2c5d785d0>), ('name', <class 'str'>), ('color', <strawberry.type.StrawberryOptional object at 0x7fd2c5d78450>), ('types', <strawberry.type.StrawberryOp...
FAILED tests/projects/test_schema.py::test_schema - AssertionError: value does not match the expected value in snapshot tests/projects/snapshots/schema.gql
FAILED tests/types2/test_input.py::test_relationship_inherit[type] - AssertionError: assert [('foreign_key', <strawberry.type.StrawberryOptional object at 0x7fd2c5d6e050>), ('related_foreign_key', <strawberry.type.StrawberryOptional object at 0x7fd2c5d6d1d0>), ('one_to_one', <strawberry.type.Strawberr...
FAILED tests/types2/test_type.py::test_inherit[input] - AssertionError: assert [('id', <strawberry.type.StrawberryOptional object at 0x7fd2c5eaeed0>), ('boolean', <class 'bool'>), ('string', <class 'str'>)] == [('id', strawberry.scalars.ID), ('boolean', <class 'bool'>), ('string', <class ...
FAILED tests/types2/test_type.py::test_relationship_inherit[input] - AssertionError: assert <strawberry.type.StrawberryOptional object at 0x7fd2c5de8090> == <class 'strawberry_django.fields.types.DjangoModelType'>
```

**Comment by skilkis** [comment]
@bellini666 I just got home, glad to see that you found the reason was the caching. I'll explore what we can do better with respect to the caching now 😊

**Comment by bellini666** [comment]
> @bellini666 I just got home, glad to see that you found the reason was the caching. I'll explore what we can do better with respect to the caching now blush

Hey @skilkis . For strawberry-graphql-django the issue was indeed the cache. After the fix everything is fine :)

But I'm not sure if the cache the only culprit. @patrick91 opened this after [this comment on discord](https://discord.com/channels/689806334337482765/689806334815764511/1126152718818488361).

Because of the fix on strawberry django, I also tried disabling the cache in here to see if it would fix gazorby's repro, but it did not.

Not sure why the same issue doesn't happen on strawberry-graphql-django though, because I also use the `InputExtension` in there and it works fine.

**Comment by skilkis** [comment]
See #2925 for the fix 😊

**Comment by patrick91** [comment]
I'm going to merge this PR as it does a couple of improvements to the tests 😊

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @patrick91 for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Pull request merged**
