### PR TITLE
Support schema extensions for subsctriptions - Alternative

### PR DESCRIPTION
**Pull request by kristjanvalur**
Subscriptions are now executed like queries and mutations, and extension hooks are called.
Result extension hooks are called for each result yielded by the subscription

Note, This is a separate PR from #2784, because it contains an alternative, less intrusive, way to do this.
It avoids changing the signature of `schema.subscribe` which now, like `graphql-core`, continues to return __either__
an `ExcecutionResult` or an `AsyncGenerator`.

## Description

the `Schema.subscribe()`, when _awaited_ returns a `Union[ExeuctionResult, AsyncGenerator[ExecutionResult,None]]`.
This is similar to before, but previously it would return a raw `GraphQLExecutionResult` object, or an `AsyncIterator` over said type, directly from `graphql-core`.

Internally, an `AsyncGenerator` is created which yields an extra _initial result_, which is either a `ExecutionResult` in case
the inner subscribe method failed and no iterator is forthcoming, or a `None` if subscription is about to proceed.  An
outer method examines this initially yielded value and either returns that to the caller, or the already started `AsyncGenerator`, which the caller then continues to iterate from, maintaining all context which that iterator had already established.

Tests are added to tests for result extensions.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* #2097

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as we

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Subscriptions now support Schema Extensions.


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @kristjanvalur for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by botberry** [comment]
# Pre-release
:wave:

Releasing commit [cb3949a7b39ac1d4d5362bef01349863c9ae3d2e] to PyPi as pre-release! :package:

**Comment by botberry** [comment]
# Pre-release
:wave:

Pre-release **0.196.0.dev.1689676980** [cb3949a7b39ac1d4d5362bef01349863c9ae3d2e] has been released on PyPi! :rocket:
You can try it by doing:

```shell
poetry add strawberry-graphql==0.196.0.dev.1689676980
```

**Comment by kristjanvalur** [comment]
Performance regression is expected when all of the schema extension boilerplate code is added on top of a trivial method.
I suspect that if we add a performance test which tests iterating over 1000 entries of a subscription, that will perform much more favourably

**Pull request closed without merging**
