### PR TITLE
Make field typing more specific

### PR DESCRIPTION
**Pull request by jordangarside**
Improves `field` typing using overloading and `StrawberryField` typing using generics.

## Description

`field` could not be used as a decorator in strict codebases as there was no way for MyPy to know whether or not it was going to return a decorator or `Any`.

https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-untyped-decorators

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Improve typing for `field` and `StrawberryField`.

**Comment by patrick91** [comment]
@jaydenwindle this looks good, but I want to test it before merging, just want to make sure we cover all the cases :)

what mypy config do you use?

**Comment by jordangarside** [comment]
MyPy Config
```ini
[mypy]
plugins = ./strawberry/ext/mypy_plugin.py
implicit_reexport = False
disallow_untyped_decorators = True
```

Example
```py
import strawberry


def some_resolver() -> str:
    return ""


@strawberry.type
class Example:
    a: str
    b: str = strawberry.field(name="b")
    c: str = strawberry.field(name="c", resolver=some_resolver)
    d: str = strawberry.field(resolver=some_resolver)

    @strawberry.field(description="ABC")
    def e(self, info) -> str:
        return ""

    @strawberry.field(name="f")
    def f_resolver(self, info) -> str:
        return ""
```

^ this will should error on the decorators without the changes from the PR.

We can't turn `disallow_untyped_decorators` for the entire codebase because there are a few other decorators that would also need to be addressed.

**Comment by patrick91** [comment]
@jordangarside I pushed some tests, but mypy is currently failing for some reason 🤷‍♂️  I'll try to understand why we get the error we are actually trying to fix:

```
error: Untyped decorator makes function "e" untyped
```

**Review by patrick91 — APPROVED** [review]
Nice one, I added a test, unfortunately for now we can enable disallow_untyped_decorators on our codebase (unless I split the mypy config for the tests) 😊

Just wanted to add a note, we will probably change the type of `@strawberry.field` in future, but that shouldn't affect existing code :)

**Pull request merged**
