### PR TITLE
Include `field_nodes` in Strawberry info object.

### PR DESCRIPTION
**Pull request by coady**
## Description

The new Info wrapper omitted the `field_nodes`.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
@coady thanks for this, what do you use field nodes for? I'd like to see if we can abstract it from what graphql-core provides :)

**Comment by coady** [comment]
> @coady thanks for this, what do you use field nodes for? I'd like to see if we can abstract it from what graphql-core provides :)

My project uses most of it, to determine [projected fields](https://github.com/coady/graphique/blob/e4f55a4df50318a6e2487984ff535b031fb18572/graphique/service.py#L119) for a data store.

But if the goal to move away from `graphql-core`, I think this will occur generally. The `GraphQLResolveInfo` object is considered part of the GraphQL spec. `OperationDefinitionNode` is also still `graphql-core`.

**Comment by patrick91** [comment]
> > @coady thanks for this, what do you use field nodes for? I'd like to see if we can abstract it from what graphql-core provides :)
> 
> My project uses most of it, to determine [projected fields](https://github.com/coady/graphique/blob/e4f55a4df50318a6e2487984ff535b031fb18572/graphique/service.py#L119) for a data store.

Nice, do you think we can find an abstraction that makes it easier to use it for you?

> But if the goal to move away from `graphql-core`, I think this will occur generally. The `GraphQLResolveInfo` object is considered part of the GraphQL spec. 

Where did you see this?

**Comment by coady** [comment]
> Nice, do you think we can find an abstraction that makes it easier to use it for you?

Sure, but it would need to replicate the recursive [Field](https://spec.graphql.org/June2018/#sec-Language.Fields) object.

> > But if the goal to move away from `graphql-core`, I think this will occur generally. The `GraphQLResolveInfo` object is considered part of the GraphQL spec.
> 
> Where did you see this?

I was referring to the [resolver docs](https://graphql.org/learn/execution/#root-fields-resolvers) and the [reference implementation](https://graphql.org/graphql-js/type/#graphqlobjecttype) linked there. I didn't mean to imply that `graphql-core` followed a struct exactly, just that the same data (including fields) should be there.

**Comment by patrick91** [comment]
@coady I think if we can make this field_nodes better we should 😊 if this is breaking your project we can merge and improve it in future (I think we can even change the name `selected_fields` might make more sense).

What do you think?

**Comment by coady** [comment]
> @coady I think if we can make this field_nodes better we should 😊 if this is breaking your project we can merge and improve it in future (I think we can even change the name `selected_fields` might make more sense).
> 
> What do you think?

Sounds great (both). Thanks.

**Comment by patrick91** [comment]
@coady I'll merge this for now, hopefully I'll have some time in future to find an abstraction 😊

**Review by patrick91 — APPROVED** [review]

**Pull request merged**
