### PR TITLE
Focus error handling when parsing `graphql_transport_ws` messages

### PR DESCRIPTION
**Pull request by kristjanvalur**
Move the parsing and exception handling of incoming messages away from actually executing the handler
## Description

Any type errors or key errors that would occur within the message handlers themselves that weren't explicitly caught would percolate up to the message parsing handler and be classified as an invalid incoming message.  This would hide errors that occur during development or other unexpected errors.

## Types of Changes

- [x] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #1762 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Exeptions from handler functions in graphql_transport_ws are no longer 
incorrectly caught and classified as message parsing errors.


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @kristjanvalur for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by BryceBeagle — APPROVED** [review]
LGTM, @patrick91 thoughts?

**Review by patrick91 — APPROVED** [review]
hi @kristjanvalur sorry for the late review, it does look good to me 😊

also thanks @BryceBeagle for reviewing this too and pinging me 😊

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
