### PR TITLE
Drop setup.py 

### PR DESCRIPTION
**Pull request by nrbnlulu**
## Description
setup.py was kept only for github to resolve dependencies graph though 
[github can now](https://github.blog/changelog/2021-10-20-dependency-graph-now-supports-the-poetry-package-manager/) resolve dependencies from poetry.lock.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation
- [x] Maintenance 

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by patrick91** [comment]
@nrbnlulu do you have any example of project without setup.py that also show used by? that's the only reason I added it, see: https://patrick.wtf/posts/til-how-to-show-dependents-packages-on-github-when-using-poetry

**Comment by nrbnlulu** [comment]
@patrick91 here https://github.com/nrbnlulu/strawberry-django-jwt/network/dependencies

**Comment by patrick91** [comment]
> @patrick91 here https://github.com/nrbnlulu/strawberry-django-jwt/network/dependencies

mmh, that's empty, I'm talking about the dependents:

image

**Comment by nrbnlulu** [comment]
ohh i missed that..

**Comment by patrick91** [comment]
> ohh i missed that.. In that case I see that poetry itself has no dependents so this is probably a bug

yeah, I wonder if we can nudge someone at GitHub to fix it, but no idea who to talk to 😊

**Pull request closed without merging**
