### PR TITLE
Refactor ASGI application

### LINKED ISSUE #19: Add option to enable/disable logging in server

### LINKED ISSUE #32: Add tests for starlette server

### LINKED ISSUE #43: Convert Starlette App to ASGI 3

### PR DESCRIPTION
**Pull request by patrick91**
This is a refactoring of the current implementation of the ASGI server, it will still be based on Starlette but it is going to use ASGI 3, meaning that can be used with any server implementing ASGI 3.

# TODO:

- [x] make web sockets test non-flaky
- [x] add and test support of errors in web sockets
- [x] remove old starlette code
- [x] more (cleanups?)

Closes #43 
Closes #32
Closes #19

### CODE REVIEW

**Comment by patrick91** [comment]
Schema for testing this (save as demo.py):

```python
import asyncio
import strawberry
import typing
import time


@strawberry.type
class Query:
    hello: str = "example"


@strawberry.type
class Subscription:
    @strawberry.subscription
    async def time(self, info) -> typing.AsyncGenerator[str, None]:
        while True:
            await asyncio.sleep(1)

            yield time.strftime("%H:%M:%S")


schema = strawberry.Schema(query=Query(), subscription=Subscription())
```

how to test

```
poetry run strawberry server demo
```

**Comment by patrick91** [comment]
Need to check why CTRL+C on the server returns an error:

```
^CERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Users/patrickarminio/.pyenv/versions/3.7.3/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 146, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/middleware/errors.py", line 87, in __call__
    await self.app(scope, receive, send)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/middleware/cors.py", line 68, in __call__
    await self.app(scope, receive, send)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/exceptions.py", line 49, in __call__
    await self.app(scope, receive, send)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/routing.py", line 265, in __call__
    await self.app(scope, receive, send)
  File "/Users/patrickarminio/Documents/personal/strawberry/strawberry/asgi/__init__.py", line 45, in __call__
    await self.handle_websocket(scope=scope, receive=receive, send=send)
  File "/Users/patrickarminio/Documents/personal/strawberry/strawberry/asgi/__init__.py", line 78, in handle_websocket
    message.get("payload"), operation_id, websocket
  File "/Users/patrickarminio/Documents/personal/strawberry/strawberry/asgi/__init__.py", line 117, in start_subscription
    operation_id,
  File "/Users/patrickarminio/Documents/personal/strawberry/strawberry/asgi/__init__.py", line 142, in _send_message
    return await websocket.send_json(data)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/websockets.py", line 116, in send_json
    await self.send({"type": "websocket.send", "text": text})
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/starlette/websockets.py", line 68, in send
    await self._send(message)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 204, in asgi_send
    await self.send(data)
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/websockets/protocol.py", line 462, in send
    yield from self.ensure_open()
  File "/Users/patrickarminio/Library/Caches/pypoetry/virtualenvs/strawberry-graphql-py3.7/lib/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by florimondmanca** [comment]
I’m leaving this comment a single non-user of Strawberry, came from Twitter. :-)

‪Can’t say for the code (although it looks pretty sweet at first sight), but the idea of adding ASGI3 support is lovely. 👍

I notice Strawberry has a dev server, but once this is in you’ll have access to all ASGI web servers (eg uvicorn) basically for free. Do you plan to switch?

**Comment by patrick91** [comment]
@florimondmanca good question! I didn’t think of that, what would be advantage? I think I’d still need some stuff from starlette, like responses and websockets

**Comment by florimondmanca** [comment]
Oh you can keep Starlette, it’s a separate thing from the server.

The main thing about ASGI is that it’s a standard interface between the server and the app — so as long as the app complies, you can use anything you want in it, including Starlette’s responses and WS classes.

In terms of pros you’d get the robustness associated with the existing servers (uvicorn, Daphne and hypercorn, which have been around for more than a year each), and not have to build your own. :) Also uvicorn seems to be the standard ASGI server so a lot of people know about it already. It’s one less item to learn to use Strawberry.

I adopted this approacjh (uvicorn as the recommended server + Starlette for application-side helpers) for [tartiflette-starlette](https://github.com/tartiflette/tartiflette-starlette), an ASGI wrapper I wrote for Tartiflette, another async GraphQL engine (they seem to be flourishing these days!), and I believe people over at Ariadne did too. It works really well because that’s what ASGI was basically made for. :)

**Comment by patrick91** [comment]
@florimondmanca sorry I'm still confused, but do you mean to replace this part of debug server to not use starlette? https://github.com/strawberry-graphql/strawberry/blob/f2df7fa2312242e73ac4afcc6001a2f2fc32a2f9/strawberry/cli/__init__.py#L35-L48

The GraphQL App I have is only using the helpers from Starlette, but it should work with any ASGI server (haven't tested, but it should work :) )

**Comment by florimondmanca** [comment]
Oh OK, nevermind, my bad. 🤦‍♂ 

I thought that `strawberry server ...` was running *its own* ASGI server… but obviously, it's uvicorn with some neat defaults. I really should have looked up the code. 😆 

> The GraphQL App I have is only using the helpers from Starlette, but it should work with any ASGI server (haven't tested, but it should work :) )

Yes since the `GraphQL` app implements ASGI, it could be served as a standalone app via Uvicorn.

**Comment by aniav** [comment]
Heya! 👋 
As a person not using asgi in everyday life I feel the code in `asgi` module could use some docstrings and comments. I imagine if something would break for me while using Strawberry I would go to the module and try to check what's happening, and why 🙌 🙂

**Comment by patrick91** [comment]
@aniav good, I'll update the code!

**Comment by patrick91** [comment]
I'm going to merge this for now and update the code with documentation later, as this is blocking other PRs :)

**Pull request merged**
