### PR TITLE
fix: upgrade pytest-flask to 1.3.0 to fix some unit testing issues

### PR DESCRIPTION
**Pull request by bellini666**

### CODE REVIEW

**Comment by patrick91** [comment]
From #3162 looks like we can remove pytest-flask :D

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @_bellini666 for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by bellini666** [comment]
> From #3162 looks like we can remove pytest-flask :D

Oh, even better!

Well, let me know if you want to drop this or not. It is probably good to merge, I didn't add any `RELEASE.md` because it only affects tests, so I don't think it is worth producing a new release for it.

**Comment by patrick91** [comment]
I think we can close it, so we don't cause merge conflicts 🗡️

**Pull request closed without merging**
