### PR TITLE
Disable implicit reexport

### PR DESCRIPTION
**Pull request by jordangarside**
This disables [implicit re-export](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport) of modules. This is one of the stricter rules in MyPy and if someone is using this project and that flag then they will not be able to import modules off of the top level modules.

```
import strawberry

@strawberry.field
...
```

Would throw an implicit reexport error for a user.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by BryceBeagle** [comment]
Would it be better to use `__all__`?

**Comment by patrick91** [comment]
Looks like using `__all__` might be a cleaner solution:

https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport

```
# This won't re-export the value
from foo import bar
# This will re-export it as bar and allow other modules to import it
from foo import bar as bar
# This will also re-export bar
from foo import bar
__all__ = ['bar']
```

**Comment by jordangarside** [comment]
Yeah I'm indifferent. The reason I didn't use `__all__` is because we have some `__init__` files that also have full classes in them. It's a bit more verbose to also add these to `__all__` instead of just explicitly re-export.

I'll update it.

**Comment by patrick91** [comment]
@jordangarside I think I'd prefer to use `__all__`, seems a lot nicer, since we are reexporting a lot of things.

I wasn't able to find a linting rule for it, do you know if flake8 has it?

**Comment by jordangarside** [comment]
There isn't an off-the-shelf one. It also turns out we don't only need this in `__init__` files since we also re-export from other files. I'm just going with this for now.

Just something people will have to be aware of as a potential source of confusion/issues (different exporting depending on if `__all__` is in the file or not).

**Comment by jordangarside** [comment]
Updated the PR with `__all__` syntax.

**Review by patrick91 — APPROVED** [review]
Nice one! I honestly didn't about this flag in mypy, might try at work 😊

I'm going to push a commit to remove the __version__ as we don't really update that :)

**Pull request merged**
