### PR TITLE
Remove the deprecated sentry tracing extension

### LINKED ISSUE #3590: `strawberry.extensions.tracing.sentry` will be impossible to import with `sentry-sdk>=3.0.0`
Hi, I am one of the maintainers of the [Sentry Python SDK](https://github.com/getsentry/sentry-python).

I am writing in to let you know about a change in our next major release (likely `3.0.0`), which will break [`strawberry.extensions.tracing.sentry`](https://github.com/strawberry-graphql/strawberry/blob/f4ecb673513ea1e4a807b687c79a2320bd0a0e43/strawberry/extensions/tracing/sentry.py#L136) by making it impossible to import this module when `sentry-sdk>=3.0.0` is installed. Specifically, we [will remove `sentry_sdk.configure_scope`](https://github.com/getsentry/sentry-python/pull/3406), which you are [importing](https://github.com/strawberry-graphql/strawberry/blob/f4ecb673513ea1e4a807b687c79a2320bd0a0e43/strawberry/extensions/tracing/sentry.py#L9) in the `strawberry.extensions.tracing.sentry` module.

Since the Sentry tracing module built into Strawberry is already deprecated (`sentry-sdk` natively supports Strawberry now), I would recommend removing the `strawberry.extensions.tracing.sentry` module completely. Otherwise, it would be a good idea to handle the `ImportError` or to migrate to the new API replacing `configure_scope`.

We still have no timeline on when we are releasing Sentry SDK `3.0.0`, but it will likely only be released several weeks or months from now – so, you still have time before this breaks. Just wanted to give a heads up.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3590">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3590/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by DoctorJohn**
## Description

After a one-year deprecation period, this PR removes the `SentryTracingExtension` provided by Strawberry in favor of the official Sentry SDK integration.

We might need to coordinate this with Sentry. It looks like their integration will assume Strawberry is not installed at all when our (deprecated) extensions cannot be imported:

https://github.com/getsentry/sentry-python/blob/1e73ce9fa12ea04250a708c14531d94827501a1d/sentry_sdk/integrations/strawberry.py#L28-L39

I created an upstream PR addressing this: https://github.com/getsentry/sentry-python/pull/3649

## Issues Fixed or Closed by This PR

* Closes #3590

## Summary by Sourcery

Remove the deprecated SentryTracingExtension in favor of the official Sentry SDK integration after a one-year deprecation period. Update documentation and remove related tests and files.

Documentation:
- Update documentation to reflect the removal of the deprecated SentryTracingExtension and guide users to use the official Sentry SDK integration.

Tests:
- Remove tests related to the deprecated SentryTracingExtension.

Chores:
- Delete the SentryTracingExtension and its related files from the codebase.

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

After a year-long deprecation period, the `SentryTracingExtension` has been
removed in favor of the official Sentry SDK integration.

To migrate, remove the `SentryTracingExtension` from your Strawberry schema and
then follow the
[official Sentry SDK integration guide](https://docs.sentry.io/platforms/python/integrations/strawberry/).



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @NucleonJohn for the PR 👏

After a year-long deprecation period, the `SentryTracingExtension` has finally been removed in favor of the official Sentry SDK integration.

Checkout out our migration guides if you have not migrated yet.

👇 https://strawberry.rocks/release/(next)
```

**Review by bellini666 — APPROVED** [review]
I'm a simple man. I see deprecated code being removed, I approve

**Comment by bellini666** [comment]
Btw, any reason to why the `validate-tweet` check is failing? 🤔

**Comment by DoctorJohn** [comment]
> I'm a simple man. I see deprecated code being removed, I approve

🤭 fair enough. Still waiting for Sentry to address my PR preparing the Sentry SDK for this change.

> Btw, any reason to why the validate-tweet check is failing? 🤔

Looks like the Tweet was considered too long. Only figured that out by running the action locally and removing random words from the TWEET file lol.

**Review by erikwrede — APPROVED** [review]
Nice!

**Pull request merged**
