### PR TITLE
Let type checkers know that fields are kwonly

### PR DESCRIPTION
**Pull request by paulo-raca**
This should bring mypy plugin in sync with #1187

- Set `kw_only=True` in DataclassAttribute object
- Remove code to check that `Attributes without a default cannot follow attributes with one`

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Update mypy plugin to treat all strawberry fields as kw_only


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Paulo Costa for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by paulo-raca** [comment]
Currently marked as `draft` because it somehow breaks mypy checks for Unions.

I really have no idea what is going on, any ideas? :sweat_smile:

**Comment by patrick91** [comment]
> Currently marked as `draft` because it somehow breaks mypy checks for Unions.
> 
> I really have no idea what is going on, any ideas? 😅

That's the same reason I didn't do this just yet, I have no idea at all, but will try to understand again 😊

**Comment by patrick91** [comment]
@paulo-raca I've changed the type hints for union a bit, they weren't really used, for mypy we have a plugin that makes it work anyway. Pyright just fails at the moment, we should implement the alternative syntax described here: https://github.com/strawberry-graphql/strawberry/issues/2000

**Review by patrick91 — APPROVED** [review]
Looks pretty good! I've also updated the code for Pyright 😊 

Not sure what happened with the issue on unions, but using collection seems to have fixed it :)

**Comment by paulo-raca** [comment]
Neat, thanks!

**Pull request merged**
