### PR TITLE
Fix incorrect docstring for `to_base64` Relay util

### PR DESCRIPTION
**Pull request by gbannerman**
## Description

This change fixes the docstring for the `to_base64` function in the Relay utils module. The docstring incorrectly stated that the return type was a tuple, but it is actually the base64 encoded global ID string. I think this was a copy/paste mistake from the `from_base64` function.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Gavin Bannerman for the PR 👏

Get it here 👉 https://strawberry.rocks/release/(next)
```

**Review by patrick91 — COMMENTED** [review]
Looks good, do you also want to make a patch release for this? 😊

**Comment by gbannerman** [comment]
> Looks good, do you also want to make a patch release for this? 😊

@patrick91 I've amended my commit and added a patch release file now ✅

**Review by patrick91 — APPROVED** [review]
Perfect!

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
