### PR TITLE
Broaden resolver type hint in strawberry.field

### PR DESCRIPTION
**Pull request by lonelyteapot**
## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #1946 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

---
I'm not sure if this needs a release

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Dmitry Semenov for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by lonelyteapot** [comment]
Pyright now seems to have an opposite issue when passing a callable with no arguments.
That doesn't seem like intended behavior. Ellipsis should match an empty argument list too.
image

I'll submit a fix with a union `Callable[[], T] | Callable[[...], T]`.

**Comment by lonelyteapot** [comment]
My bad, didn't pay enough attention. Should work now.

**Comment by patrick91** [comment]
Hi @lonelyteapot, I think I accidentally fixed this while fixing other typing issues in #2172!

Thanks for the PR though 😊

**Pull request closed without merging**
