### PR TITLE
Add support for Federation 2.3

### PR DESCRIPTION
**Pull request by patrick91**
This PR updates our federation directive to support 2.1, 2.2 and 2.3.

It adds:

`@composeDirective`, which can be added by adding `compose=True` when using
`strawberry.federation.schema_directive`, it is used to keep the schema directive
on the composed supergraph.

Updates the shareable directive to be repeatable, this doesn't really affect
anything at runtime, but it will be useful once we add error checking for
directives 😊

Finally it adds `strawberry.federation.interface_object` which is a quick
way to create an object type type with the `@interfaceObject` directive.
(It is used to extend an interface from a subgraph)

# TODO:

- [x] Add docs
- [ ] Add some error checking (optional, can be done in another PR)

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @patrick91 for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by botberry** [comment]
## Apollo Federation Subgraph Compatibility Results

<table>
<thead>
<tr><th>Federation 1 Support</th><th>Federation 2 Support</th></tr>
</thead>
<tbody>
<tr><td><table><tr><th><code>_service</code></th><td>🟢</td></tr><tr><th><code>@key (single)</code></th><td>🟢</td></tr><tr><th><code>@key (multi)</code></th><td>🟢</td></tr><tr><th><code>@key (composite)</code></th><td>🟢</td></tr><tr><th><code>repeatable @key</code></th><td>🟢</td></tr><tr><th><code>@requires</code></th><td>🟢</td></tr><tr><th><code>@provides</code></th><td>🟢</td></tr><tr><th><code>federated tracing</code></th><td>🔲</td></tr></table></td><td><table><tr><th><code>@link</code></th><td>🟢</td></tr><tr><th><code>@shareable</code></th><td>🟢</td></tr><tr><th><code>@tag</code></th><td>🟢</td></tr><tr><th><code>@override</code></th><td>🟢</td></tr><tr><th><code>@inaccessible</code></th><td>🟢</td></tr><tr><th><code>@composeDirective</code></th><td>🔲</td></tr><tr><th><code>@interfaceObject</code></th><td>🔲</td></tr></table></td></tr>
</tbody>
</table>

Learn more:
* [Apollo Federation Subgraph Specification](https://www.apollographql.com/docs/federation/subgraph-spec/)
* [Compatibility Tests](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/COMPATIBILITY.md)

**Comment by botberry** [comment]
# Pre-release
:wave:

Releasing commit [97a2203e5685d170e0ab70e598e49b5a613ed823] to PyPi as pre-release! :package:

**Comment by botberry** [comment]
# Pre-release
:wave:

Pre-release **0.157.0.dev.1676507628** [97a2203e5685d170e0ab70e598e49b5a613ed823] has been released on PyPi! :rocket:
You can try it by doing:

```shell
poetry add strawberry-graphql==0.157.0.dev.1676507628
```

**Comment by patrick91** [comment]
I need to update the schema to also include a link to import the directive:

```
schema @composeDirective(name: "@myDirective")
@link(url: "https://strawberry.rocks/abc/v1.2", import: ["@myDirective"])
@link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@composeDirective", "@inaccessible", "@key", "@shareable", "@tag"]) {
  query: Query
}
```

The url is not important, but should ideally point to a spec. We can allow this:

```python
@strawberry.federation.schema_directive(
    locations=[Location.OBJECT], name="cacheControl", compose=True, import_from="a_url"
)
class CacheControl:
    max_age: int
```

the url needs to validated, format should be something like `https://strawberry.rocks/abc/v1.2`

**Comment by patrick91** [comment]
should be good to go now!

**Pull request merged**
