### PR TITLE
Consolidate websocket protocol tests

### PR DESCRIPTION
**Pull request by kristjanvalur**
Move tests for the websocket protocols (`graphql_ws`, `graphql_transport_ws`) into a separate place (`tests/websocket`)
where they can be parametrized and run on the four different integration which support websockets.

## Description

Previously, websocket tests were duplicated for the `aiohttp`, `asgi`, `fastapi` and `channels` integrations, with both
protocols having a full set of tests in each.

Following what has been previously done with `http`, we now extend the abstract `HttpClient` classes in `tests/http/clients`
to provide async websocket functionality, parametrize the unit tests, and write them once.

This makes it easier to maintain a coherent set of unittests for the websocket protocols, while ensuring that they
do get executed for all of the available integrations.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #2610 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @kristjanvalur for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by patrick91 — APPROVED** [review]
I like this a lot, thanks! :D

CleanShot 2023-03-15 at 00 25 36@2x

I'm going to remove the release file, hope that's ok! I think we can skip the release since we are updating just tests 😊

**Comment by patrick91** [comment]
@kristjanvalur I can't push, can you remove the release file? 😊

**Comment by kristjanvalur** [comment]
yes, about the pushes, I'm using an organization repo for this, policy doesn't permit external pushes.

**Pull request merged**
