### PR TITLE
Added ability to dynamically update the Response `status_code` in the `MaskErrors` extension

### PR DESCRIPTION
**Pull request by jerber**
## Description

Add a new optional field `status_code_hook` to the `MaskErrors` extension to allow dynamically setting the Response `status_code`.

`status_code_hook` takes in an optional function of `Callable[[GraphQLError, ExecutionContext], None]` so you can update the Response, which you get from the `execution_context`, dynamically per error.

I'm using this in our app like so:

```

def should_mask_error(error: GraphQLError) -> bool:
    original_error = error.original_error
    if original_error and isinstance(
        original_error, (DisplayException, PermissionError)
    ):
        return False
    return True


def status_code_hook(error: GraphQLError, execution_context: ExecutionContext) -> None:
    if should_mask_error(error):
        execution_context.context.response.status_code = (
            settings.internal_server_error_status_code
        )
    else:
        status_code = settings.display_error_status_code
        original_error = error.original_error
        if original_error and isinstance(original_error, DisplayException):
            status_code = (
                original_error.status_code or settings.display_error_status_code
            )
        execution_context.context.response.status_code = status_code

MaskErrors(
        error_message="Internal Server Error",
        should_mask_error=should_mask_error,
        status_code_hook=status_code_hook,
)
```

I've also updated the docs to reflect this change.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Fixes https://github.com/strawberry-graphql/strawberry/issues/2276

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Jeremy Berman for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by AndrewIngram** [comment]
How would conflicting status codes be managed here?

Say the response document contains multiple errors, and the first error handled sets a 500, and a later one sets something else, say a 412. Right now, the latter would win, even if the 500 is arguably more correct -- intuitively i'd expect the most "serious" error to win.

**Comment by jerber** [comment]
> How would conflicting status codes be managed here?

Good point @AndrewIngram. I wanted to make this a function so that you could add this logic if you wanted. For example:

```python
import strawberry
from strawberry.extensions import MaskErrors
from graphql.error import GraphQLError
from strawberry.types import ExecutionContext

class VisibleError(Exception):
    pass

def status_code_hook(error: GraphQLError, execution_context: ExecutionContext) -> None:
    response = execution_context.context['response']
    existing_status_code = response.status_code
    if error.original_error and isinstance(error.orginal_error, VisibleError):
        new_status_code = 400
    else:
        new_status_code = 500
    if new_status_code > existing_status_code:
        response.status_code = new_status_code

schema = strawberry.Schema(
    Query,
    extensions=[
        MaskErrors(status_code_hook=status_code_hook),
    ]
)
```

I just updated the RELEASE.md and example in docs to reflect this.

**Comment by patrick91** [comment]
> @jerber I'm not sure it makes sense to put this logic in the `MaskErrors` extension, I think it probably needs its own extension.
> 
> Also I would be careful about modifying the status code of the response based on any errors because it might contravene the GraphQL over HTTP spec: https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes . Because a GraphQL server can return partial data it should always return a 200 unless it cannot generate a well formed response.

+1 for this

@jerber what are the use cases for updating the status code?

**Comment by jerber** [comment]
@jkimbo @patrick91 I agree, it should be in a different extension. Although maybe I'll just open source an example of how I'm changing the status codes since the whole thing is really just one function.

My main use case for updating status codes is for webhooks that use the status code to signal success or failure. For example, Stripe uses response status codes to know whether to retry a webhook.

**Comment by jerber** [comment]
I created this extension which takes in the function `status_code_from_error` that returns an optional status code given the error. @patrick91 let me know if you think it's worth me creating a pull request for this, I can see how it can be used against the best practices of the GQL spec.

```
import typing as T
from strawberry.extensions import Extension
from graphql.error import GraphQLError


class UpdateStatusCode(Extension):
    """This must go before MaskErrors so that you get the `error.original_error`"""

    status_code_from_error: T.Callable[[GraphQLError], T.Optional[int]]

    def __init__(
        self, status_code_from_error: T.Callable[[GraphQLError], T.Optional[int]]
    ):
        self.status_code_from_error = status_code_from_error

    def on_request_end(self) -> None:
        result = self.execution_context.result
        if result and result.errors:
            response = self.execution_context.context.response
            max_status_code = response.status_code
            for error in result.errors:
                if error.original_error:
                    error_status_code = self.status_code_from_error(error)
                    if error_status_code is not None and error_status_code > (
                        max_status_code or 0
                    ):
                        max_status_code = error_status_code
            if max_status_code is not None:
                response.status_code = max_status_code
```

**Comment by jkimbo** [comment]
> My main use case for updating status codes is for webhooks that use the status code to signal success or failure. For example, Stripe uses response status codes to know whether to retry a webhook.

@jerber I don't understand this use case. Are you saying that you've setup Stripe to send a GraphQL query to your API server?

**Comment by jerber** [comment]
> Are you saying that you've setup Stripe to send a GraphQL query to your API server?

@jkimbo right. For example, Stripe sends a call to our server when a user adds a bank account. Stripe will retry this call if they don't receive a 200 response, so if there's some sort of internal error when processing this info, I want to return a non 200 so Stripe knows to retry later. I have this pattern for a few other services as well.

I can always just make Stripe hit a REST endpoint but I wanted to keep these calls in GraphQL land, so I found setting the status_code for certain exceptions was easiest.

**Comment by AndrewIngram** [comment]
> I can always just make Stripe hit a REST endpoint but I wanted to keep these calls in GraphQL land, so I found setting the status_code for certain exceptions was easiest.

Personally i'd bypass GraphQL for this kind of thing, there's no real value in it here;  and as you've already seen, it presents avoidable challenges. There's no reason why GraphQL has to be the only interface between your system and the internet.

**Comment by jerber** [comment]
> @jerber but how do you know that it's stripe that is calling your GraphQL endpoint? Presumably stripe is not making a GraphQL request it's just making a POST call with some data. 


Stripe sends a header that is decoded by a secret key the server has.

**Comment by jerber** [comment]
@AndrewIngram yeah I ended up creating REST endpoints for this.

**Comment by jkimbo** [comment]
Ok I'm going to close this issue now because it sounds like you've solved this issue in another way.

**Pull request closed without merging**
