### PR TITLE
Add benchmarks from `strawberry-graphql/benchmarks`

### PR DESCRIPTION
**Pull request by adriencaccia**
## Description

Move the benchmarks defined in https://github.com/strawberry-graphql/benchmarks in this repo. That way they will benefit from https://codspeed.io/ 😄 
Also bumped the version of `pytest-codspeed` to https://github.com/CodSpeedHQ/pytest-codspeed/releases/tag/v2.0.1, which contains your contribution @patrick91 😉 

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @adriencaccia for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by adriencaccia** [comment]
> Hi, thanks for contributing to Strawberry 🍓!
> 
> We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!
> ...
@patrick91 since this PR only affects benchmarks, there is nothing to release. Is there a way to make the `Release file check` workflow pass for this kind of contribution?

**Comment by patrick91** [comment]
@adriencaccia it is fine to ignore the release check for this PR 😊

**Comment by adriencaccia** [comment]
@patrick91 The profiles are now available on the benchmarks:
image

Since we activated profiling, the regressions on the existing benchmarks are expected and explained in https://github.com/CodSpeedHQ/pytest-codspeed/releases/tag/v2.0.0.
They are safe to acknowledge and merge. It will create a new baseline that will stay stable!

**Review by patrick91 — APPROVED** [review]
exciting! thanks! 😊

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
