### PR TITLE
Fix strawberry mypy pluging for pydantic v2

### PR DESCRIPTION
**Pull request by Corentin-Br**
## Description

It fixes mypy plugin for pydantic v2

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*https://github.com/strawberry-graphql/strawberry/issues/3079

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Fix strawberry mypy plugin for pydantic v2



Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Corentin-Br for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by patrick91** [comment]
Hi @Corentin-Br! Thanks for the PR, what's the easiest way to reproduce the error?

**Comment by Corentin-Br** [comment]
> Hi @Corentin-Br! Thanks for the PR, what's the easiest way to reproduce the error?

```python
class MyPydanticModel(BaseModel):
    ...
@strawberry.experimental.pydantic.input(model=MyPydanticModel)
class MyStrawberrytInput:
    ...
```

That should reproduce it when mypy goes over the strawberry decorator.
I didn't really look for a MRE.

The fix is identical to the previous fix that was done for V1 (https://github.com/strawberry-graphql/strawberry/pull/3019)

**Comment by g-as** [comment]
I do need one field on the pydantic Model to trigger the error:
```
import pydantic
import strawberry


class Model(pydantic.BaseModel):
    id_: int


@strawberry.experimental.pydantic.type(model=Model)
class ModelType:
    ...
```

outputs
```
Traceback (most recent call last):
  File "/home/backend/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/main.py", line 99, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/main.py", line 178, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/build.py", line 189, in build
    result = _build(
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/build.py", line 262, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/build.py", line 2938, in dispatch
    process_graph(graph, manager)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/build.py", line 3336, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/build.py", line 3431, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal_main.py", line 93, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal_main.py", line 220, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal_main.py", line 349, in semantic_analyze_target
    analyzer.refresh_partial(
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal.py", line 601, in refresh_partial
    self.refresh_top_level(node)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal.py", line 612, in refresh_top_level
    self.accept(d)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal.py", line 6493, in accept
    node.accept(self)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/nodes.py", line 1145, in accept
    return visitor.visit_class_def(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal.py", line 1610, in visit_class_def
    self.analyze_class(defn)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal.py", line 1695, in analyze_class
    self.analyze_class_body_common(defn)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal.py", line 1729, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/home/backend/.venv/lib/python3.11/site-packages/mypy/semanal.py", line 1802, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, decorator, self))
  File "/home/backend/.venv/lib/python3.11/site-packages/strawberry/ext/mypy_plugin.py", line 422, in strawberry_pydantic_class_callback
    field = PydanticModelField.deserialize(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/backend/.venv/lib/python3.11/site-packages/pydantic/mypy.py", line 382, in deserialize
    data = data.copy()
           ^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'copy'
```

**Comment by patrick91** [comment]
@g-as thank you so much!

**Comment by botberry** [comment]
# Pre-release
:wave:

Pre-release **0.209.8.dev.1697789637** [6e01b4ff74faa2b6e79374a6cb16ad87143d1d20] has been released on PyPi! :rocket:
You can try it by doing:

```shell
poetry add strawberry-graphql==0.209.8.dev.1697789637
```

**Review by patrick91 — APPROVED** [review]

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Comment by g-as** [comment]
Thank YOU

**Pull request merged**
