### PR TITLE
Link to Strawberry Django repo on main website

### PR DESCRIPTION
**Pull request by Kommandat**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* Fixes https://github.com/strawberry-graphql/strawberry/issues/987

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes. (N/A)
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by BryceBeagle — COMMENTED** [review]
Thanks for the contribution! 

I think it would just be better to make this a link in the first sentence of the file. 

```markdown
Strawberry comes with a basic [Django integration](https://github.com/strawberry-graphql/strawberry-graphql-django).
```

Also, while definitely true, we can probably leave off the last sentence, as this is just documentation.

**Comment by Kommandat** [comment]
> Thanks for the contribution!
> 
> I think it would just be better to make this a link in the first sentence of the file.
> 
> ```gfm
> Strawberry comes with a basic [Django integration](https://github.com/strawberry-graphql/strawberry-graphql-django).
> ```
> 
> Also, while definitely true, we can probably leave off your last sentence, as this is just documentation.

@BryceBeagle Updated!

**Review by BryceBeagle — APPROVED** [review]

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by BryceBeagle** [comment]
Ignore the request for a RELEASE.md as this is a minor docs-only change :slightly_smiling_face:

**Review by patrick91 — APPROVED** [review]

**Comment by patrick91** [comment]
@Kommandat Thanks for your first contribution to Strawberry! You've been invited to our organization, check your emails for the invite 😊

Also, feel free to request a sticker by filling this form 👉
https://forms.gle/dmnfQUPoY5gZbVT67

**Comment by Kommandat** [comment]
@patrick91 Thanks! Do you mind resending the invite? I think it got sent to the wrong email

**Comment by patrick91** [comment]
@Kommandat 

image

it should have gone to your GitHub email, let me know if you don't get it :)

**Comment by BryceBeagle** [comment]
Is that the same account? It's strange that it says `Lakshay Akula` twice w/o `Kommandat`

**Comment by patrick91** [comment]
Yup, same account: 

image

**Comment by Kommandat** [comment]
@patrick91 Sorry, I had the wrong email as my primary email on Github (my previous company email that I don't have access to anymore). I just fixed my primary Github email now

**Comment by patrick91** [comment]
done!

**Pull request merged**
