### PR TITLE
Add process_errors method to Schema and log errors by default

### LINKED ISSUE #840: Improve errors logging
Right now errors are being caught by GraphQL core and sent into the `errors` fields of the GraphQL response. Unfortunately that makes things harder to debug locally; we should print better exceptions locally, by using one of the following options:

```python
    def process_result(
        self, request: HttpRequest, result: ExecutionResult
    ) -> GraphQLHTTPResponse:
        data: GraphQLHTTPResponse = {"data": result.data}

            for error in result.errors:
                actual_error = error.original_error or error

                traceback.print_exception(
                    type(actual_error), actual_error, actual_error.__traceback__
                )

        return data
```

```python
    def process_result(self, request, result):
        data = super().process_result(request, result)

        # Log errors
        if result.errors:
            for error in result.errors:
                try:
                    if isinstance(error, GraphQLError) and error.original_error:
                        raise error.original_error
                    else:
                        raise error
                except Exception as error:
                    logger.exception(error)

        return data
```

### LINKED ISSUE #847: Log full back trace of error in unit tests
GraphQL catches exceptions and shows very limited amount of information from the error. This makes debugging unit tests almost impossible. It would be much better to log full back traces from errors.

For example following error message does not help much to understand the actual problem:

```
___________________________________________________ test_uuid ____________________________________________________

    def test_uuid():
        @strawberry.type
        class Query:
            @strawberry.field
            def example_uuid_out(self) -> uuid.UUID:
                return uuid.NAMESPACE_DNS

        schema = strawberry.Schema(Query)

        result = schema.execute_sync("{ exampleUuidOut }")

>       assert not result.errors
E       AssertionError: assert not [GraphQLError('', locations=[SourceLocation(line=1, column=3)], path=['exampleUuidOut'])]
E        +  where [GraphQLError('', locations=[SourceLocation(line=1, column=3)], path=['exampleUuidOut'])] = ExecutionResult(data=None, errors=[GraphQLError('', locations=[SourceLocation(line=1, column=3)], path=['exampleUuidOut'])], extensions={}).errors

tests/schema/types/test_uuid.py:17: AssertionError
```

The error message above was cause by this
```diff
--- a/strawberry/field.py
+++ b/strawberry/field.py
@@ -244,6 +244,7 @@ class StrawberryField(dataclasses.Field):
             return result

         def _strawberry_info_from_graphql(info: GraphQLResolveInfo) -> Info:
+            raise Exception()
             return Info(
                 field_name=info.field_name,
                 field_nodes=info.field_nodes,
```

### PR DESCRIPTION
**Pull request by jkimbo**
## Description

Add a new `process_errors` method to `strawberry.Schema` which logs all exceptions during execution to a new `strawberry.execution` logger.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Closes #847 
* Closes #840 

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Review by BryceBeagle — APPROVED** [review]

**Comment by la4de** [comment]
This is huge improvement to developer experience!

**Review by marcoacierno — APPROVED** [review]

**Review by patrick91 — APPROVED** [review]
Looks good to me! Do you think we should make this configurable?

**Comment by jkimbo** [comment]
> Looks good to me! Do you think we should make this configurable?

@patrick91 I pulled the process errors part into its own method so that it can at least be overridden if needed. I think let's wait until we have a good pattern for configuration and if any use cases come up.

**Comment by jokull** [comment]
The way this is done, [a default Sentry config](https://docs.sentry.io/platforms/python/guides/logging/) will capture these errors. Nice! And nice to make a method to overwrite for raising early in pytest for example.

**Comment by jokull** [comment]
Is this an opportunity to document errors?

```rest
---
title: Errors
---

# Error Handling

By default Strawberry bubbles `graphql.error.GraphQLError` errors, sending them to the client under the top level `error` key, but also logs them to a custom `strawberry.execution` logger. An application monitoring solution like Sentry will be aware of such exceptions when configured for your app. 

To overwrite this behavior, for example to raise errors early in tests, you can subclass `strawberry.schema.Schema.process_errors` which receives a list of `GraphQLError` instances and do custom error handling there.
```

**Comment by patrick91** [comment]
@jkimbo would be ok adding a bit of documentation? Maybe we can refer to this for implementing proper errors https://sachee.medium.com/200-ok-error-handling-in-graphql-7ec869aec9bc

but as @jokull says it is worth adding some text. I can do in the evening if you're busy 😊

**Comment by jkimbo** [comment]
I have a document mostly done to document error handling generally: https://www.craft.do/s/UNNckPvoqMQUDD 

I was just waiting for this PR to land so that it's accurate.

**Comment by patrick91** [comment]
@jkimbo ah, right :) I forgot! We can copy that then 😊 nice one!

**Pull request merged**
