### PR TITLE
Rename `custom_getter` variable in nested scope for FastAPI router to reflect purpose

### PR DESCRIPTION
**Pull request by garyd203**
## Description

With the FastAPI router, the custom *context getter* function is called `custom_getter`, but in the internal implementation there is an internal variable for the *context* that is also called `custom_getter`. This PR changes the name of the internal variable to reduce confusion and remove the possibility of accidental name-conflict.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes. -> covered by existing tests
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

Rename internal variable `custom_getter` in FastAPI router implementation.


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Gary Donovan for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by patrick91 — APPROVED** [review]
Makes sense! thank you 😊

**Comment by Kludex** [comment]
https://strawberry.rocks/docs/integrations/fastapi#context_getter the docs needs to be updated

**Comment by patrick91** [comment]
@Kludex what does need to changed there? isn't this change only internal? 

the code from the docs seems to still work fine

**Comment by Kludex** [comment]
Right! Sorry!

**Comment by garyd203** [comment]
Thanks @patrick91 . Yeah, I was confused too @Kludex , this PR is my attempt to reduce the confusion :-)

**Pull request merged**
