### PR TITLE
closes #158 WIP Added docs using Sphinx and markdown

### LINKED ISSUE #158: Setup docs with mkdocs
https://www.mkdocs.org

A friend of mine is working on a design for the new website which will also include the docs, but for now I think we can start with mkdocs. The new website will pull the documentation from this repo so no work will be wasted in case we start this before the new website :)

### PR DESCRIPTION
**Pull request by CarlosMart626**
Added Sphinx using markdown to create docs.

With Sphinx installed `recommonmark`, `sphinx-rtd-theme` and `sphinx-markdown-tables`.

This example includes code example using Markdown and also uses sphinx autodoc. Also included markdown file 

To build the docs run: `make build-docs-html`

example
Result example

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
Hi @CarlosMart626! I was thinking maybe we could try MkDocs, Tom has added something similar to autodocs: https://twitter.com/_tomchristie/status/1182640810594095105

But, to be fair, we will probably remove the docs tools at some point (I want to build the documentation site with Gatbsy in future) :)

Let me know what you think about MkDocs! And, just a note, I think we should put the dependencies as dev dependencies :)

**Comment by CarlosMart626** [comment]
@patrick91  Yes! I'll take a look to MKDocs I've been in some very busy weeks hope to get an updated version soon

**Comment by patrick91** [comment]
@CarlosMart626 can you hold off a moment? :D My friend finished the design and I'm working on implementing it using gatsby, so I think we might not need mkdocs after all ;)

**Comment by remorses** [comment]
i suggest that you use mkdocs with the material theme instead, i used gatsby and it is not very easy to develop with, better stay lean and remain in the python echosystem.

An example of the mkDocs material theme is [uvicorn](https://www.uvicorn.org/)

**Comment by patrick91** [comment]
@remorses that's a good point, luckily I'm pretty familiar with Gatsby so that won't be a problem :) I actually managed to implement the site already, but haven't published yet as I have to write the docs, it will be my focus on the holidays :)

PR is here if you want to have a look: https://github.com/strawberry-graphql/strawberry.rocks/pull/3

**Comment by patrick91** [comment]
I'll close this PR for now, thanks a lot @CarlosMart626! Hope to see you soon at some event 😊

**Pull request closed without merging**
