### PR TITLE
Fix typo in Schema-Basics Docs

### LINKED ISSUE #604: Schema-basics documentation uses wrong field name for books query
https://github.com/strawberry-graphql/strawberry/blob/a973af56317548925d0f57a7fac338adc6aef9fa/docs/01_general/01_schema-basics.md#L223-L231

This snippet should use `books` instead of `getBooks`

### PR DESCRIPTION
**Pull request by Paolo-Cosentino**
This pull request is in regards to Issue #604.

image

Closes #604

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by BryceBeagle** [comment]
Don't worry about the release file as this is a docs only change

**Comment by BryceBeagle** [comment]
Hey, heads up. GitHub doesn't recognize the email you made the commit with (i.e. it's not linked to your GitHub account).

I'd recommend looking at the docs [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git) and [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-on-github).

**Comment by Paolo-Cosentino** [comment]
Thx, should be fixed now.

**Comment by ulgens** [comment]
Can you please add fixes - solves keyword with issue number into PR details, so it can attach it with the issue.

**Review by ulgens — APPROVED** [review]

**Comment by patrick91** [comment]
@Paolo-Cosentino thanks for making the docs better! as @BryceBeagle mentioned your commit isn't associated with your user properly, maybe you needed to do a git commit amend, like here https://www.git-tower.com/learn/git/faq/change-author-name-email/#using---amend-for-the-very-last-commit ?

Not a big deal though, I can merge anyway, but I think it'd be nice if the commit is properly attributed to you 😊 let me know!

**Comment by Paolo-Cosentino** [comment]
@patrick91, I've gone ahead and run the command. I hope that fixes it but I'm unsure how to check. Please let me know.

**Comment by BryceBeagle** [comment]
@Paolo-Cosentino I'll try to help you out here :slightly_smiling_face: 

image

If you look at this screenshot, you can see that the commit you made didn't have your profile picture and it's not a link to a real account. This indicated that you either made your commit in Git with the wrong configuration, or you haven't told GitHub about the configuration you want to use. Because you said you were knew to this I figured you were probably unaware :slightly_smiling_face: 

You've made two commits (and a merge, but that's not relevant here) now, both with identical changes. If you look at the "patch" for the PR (you can view it by adding `.patch` to the end of the URL -> [here](https://github.com/strawberry-graphql/strawberry/pull/605.patch)), you'll see two identical commits with just the email address for the author (you) changed. This tells me that you've fixed the problem locally on your computer!

@patrick91 had you "amend" the commit, which is the easier option, and why there are two commits. It just tacks on a second commit that "fixes" the first one. Another option would have been to completely rewrite the commit and _replace_ the commit, but this is a bit more prone to error as this _overwrites_ the history of the Git tree. As we [squash and merge](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) our pull requests, the end result should end up looking the same, so there's no issue with the route you've taken.

What happened here is that Git lets you push commits from other people (one of the features of being a _decentralized_ version control system). Every commit stores the information about who created it. GitHub didn't have an association of that commit's [email address + name] with an account and just used a placeholder "unknown" user in your place. Now that you changed your local Git configuration to match what GitHub expects, your commits will be properly attributed to your account.

Hopefully this makes sense :+1:

**Review by BryceBeagle — APPROVED** [review]

**Pull request merged**
