### PR TITLE
Add SyncToAsync extension to enable use of the Django ORM in an async context

### PR DESCRIPTION
**Pull request by jkimbo**
## Description

This PR adds a new extension `SyncToAsync` that wraps all customer resolvers in the `sync_to_async` decorator so that you can use the Django ORM when using the async view. This also means that you can use dataloaders with Django.

This PR also adds a `create_model_load_fn` to make it easier to make a dataloader for a Django model.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Jonathan Kim for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by Ambro17** [comment]
Do i understand correctly that this solution of dataloaders in sync contexts would only work with django models? Is there other issue to track how to solve it if we're using a sync server but not django?

**Comment by patrick91** [comment]
@bellini666 do you want to take a look at this? do we still need it?

**Comment by bellini666** [comment]
> @bellini666 do you want to take a look at this? do we still need it?

strawberry-graphql-django already solves this same issue by making all their fields have a "safe resolve", which will get wrapped in `sync_to_async` when inside running ASGI. You just need to use `strawberry.django.field` instead of `strawberry.field` in those

But the idea here is really interesting and allows using strawberry without strawberry_django for ASGI. Although using `strawberry.django.field` has other advantages than this, specially considering the "cache" resolving that is getting added to my open PR and the optimizer stuff that will get ported from strawberry-django-plus.

The question here is if we want to have 2 ways of solving the same issue for strawberry? I'm not against it, but if we do we would probably want to modify strawberry_django to make use of this extension, maybe "enforcing" its usage, or at least the "safe_resolver" would need to be aware that it is already running inside a `sync_to_async` context to avoid doing it again (we can use `contextvars` for that)

Since this PR is from 2021, maybe it was created in a time were strawberry_django didn't exist yet (or wasn't known)?

What do you think of that all all well @jkimbo ?

**Comment by patrick91** [comment]
I'll close this, since we have it in Strawberry Django 😊

**Pull request closed without merging**
