### PR TITLE
Add activity dashboard in repo

### PR DESCRIPTION
**Pull request by patrick91**
@strawberry-graphql/core a friend of mine made this project getting infographics for GitHub projects, this dashboard seems quite useful to have (hopefilly it will motivate me to merge more PRs :D), the only thing I'm not sure user of is the the trending topics, I'll ask what they are and if we can replace with something else, maybe a list of good first issues?

### CODE REVIEW

**Comment by arraypad** [comment]
Hi all, thanks for considering adding this dashboard.

The "trending topics" component is just looking at the frequency of words in commit messages. I'm certainly open to replacing this with something which would be more useful for the project, and I'll look at how I can make this configurable for you.

A list of first good issues is a great idea. Any other suggestions? :)

**Comment by bellini666** [comment]
@patrick91 @arraypad this looks very cool! I personally love statistics, and it is also something that motivates people to contribute more.

Regarding the suggestion of a list of first good issues, it seems nice but doesn't seem too much related to an "Activity" dashboard IMO.

Another suggestion would be a small list of top contributors considering the time period of the dashboard? Something that would engage people to contribute more :)

**Comment by skilkis** [comment]
This looks awesome, great work! Just to nitpick the header is a bit hard to read in dark mode:

image

**Comment by arraypad** [comment]
Thanks San, that's a really good point too. I'll be working on this in the coming days so will share an update here once I've addressed all this :)

**Comment by arraypad** [comment]
I've made an update which generates markdown for several smaller components, so you can select which ones you feel are most useful for the project.

This update includes:
* a new top (recent) contributors component - thanks @bellini666
* better legibility in dark mode since the title is now in markdown - thanks @skilkis 
* better layout on mobile since the individual components can form a single column

You can have a play with this [on Repography](https://repography.com/app/0/strawberry-graphql/strawberry/recent-activity) but here's an example with all the components selected:

Screenshot 2022-03-21 at 10-19-04 Repography Make your GitHub repository beautiful

**Pull request merged**
