### PR TITLE
🎨 Use str magic method

### PR DESCRIPTION
**Pull request by Ambro17**
Just a cosmetic change, but a believe a useful one nonetheless. 
Being able to do `str(schema)` to print the schema seems more pythonic than `schema.as_str()`.

Perhaps you disagree, in that case you can dismiss the pr and i will take no offense

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Review by ulgens — APPROVED** [review]

**Review by patrick91 — APPROVED** [review]
I can’t remember why I did this way :D it makes sense to use `__str__`. Thank you!

**Comment by Ambro17** [comment]
Hello Pattrick, do you think we can merge this so i can start using it?

**Comment by patrick91** [comment]
@Ambro17 yes! sorry will merge now 😊

**Pull request merged**
