### PR TITLE
Move CI tests to GitHub actions

### PR DESCRIPTION
**Pull request by patrick91**
This should make it easier to test under multiple python versions (ie 3.8 beta)

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
This is blocked by GitHub not having beta python versions :( https://github.com/actions/setup-python/issues/15

**Comment by marcoacierno** [comment]
Can we merge it if it works and then update it once Github supports 3.8?

**Comment by patrick91** [comment]
@marcoacierno I think we should try to add 3.8a on Circle CI and then when it is supported on GH Actions we can migrate :)

**Comment by patrick91** [comment]
This can be merged when uvloop 0.14 gets released (as it is broken on py38)

**Pull request merged**
