### PR TITLE
Added documentation for enum type

### PR DESCRIPTION
**Pull request by karina-klinkeviciute**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

### CODE REVIEW

**Comment by patrick91** [comment]
we can ignore the release file check for this PR :)

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
I did some minor tweaks and added a new box on the site for the additional resources! Will merge now, thank you so much for this! 😊

**Comment by karina-klinkeviciute** [comment]
> I did some minor tweaks and added a new box on the site for the additional resources! Will merge now, thank you so much for this! blush

It's nice to contribute :)

**Pull request merged**
