### PR TITLE
Optimization: Improve performance of rich exceptions on custom scalar

### PR DESCRIPTION
**Pull request by paulopaixaoamaral**
## Description

The release of [0.145.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.145.0) caused a production outage for us, with all of our Heroku dyno’s (machines) seeing high CPU usage and load figures immediately after our web server, gunicorn, was booted via Heroku’s Procfile.

After the initial rollback, we discovered that lowering the number of gunicorn workers we use concurrently (via **WEB_CONCURRENCY**) from 6 to 4 helped the gunicorn workers serve requests, but we still saw elongated startup times and a CPU spike on first boot. 

This led us to [this line](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/custom_scalar.py#L103) in the 0.145.0 release, which does an intensive call; we suspect that we’re doing this call about 11 times per worker on boot. So with 6 workers - we did an intensive call over 60 times, and that took so long that the parent gunicorn process considered the workers dead and started new ones…thus we never served any requests as they continually rebooted.

The whole issue is proven by the fact we can release with no CPU spike if we disable the new error checking with the included env var (i.e., if we set `STRAWBERRY_DISABLE_RICH_ERRORS` to `false`).

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Paulo Amaral for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by patrick91 — APPROVED** [review]
Nice one, thanks! 

I think in future we'll want to find a way to run this code at all if possible, but this solution is good for the time being!

**Comment by patrick91** [comment]
@paulopaixaoamaral are you going to add a release file or do you want me to write one? 😊

**Comment by paulopaixaoamaral** [comment]
> @paulopaixaoamaral are you going to add a release file or do you want me to write one? 😊

@patrick91  I am adding a release file, it was my fault for not realising it was a requirement 🙂

**Comment by patrick91** [comment]
> > @paulopaixaoamaral are you going to add a release file or do you want me to write one? 😊
> 
> @patrick91 I am adding a release file, it was my fault for not realising it was a requirement 🙂

No worries at all!

**Review by patrick91 — APPROVED** [review]
Perfect!

**Comment by patrick91** [comment]
Our bot for the repo invitation is still broken, so I'll post the message instead :)

---

Thanks for contributing to Strawberry! 🎉 You've been invited to join the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
