### PR TITLE
testing pydantic v1.10.0a2

### PR DESCRIPTION
**Pull request by samuelcolvin**
### TO NOT MERGE

This is pull request is just to test pydantic v1.10, see https://github.com/pydantic/pydantic/discussions/4359

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Hi, please can you kick off tests so I can check if v1.10 will break anything.

**Comment by samuelcolvin** [comment]
thanks so much.

**Comment by samuelcolvin** [comment]
This might not have worked properly, I forgot to update `poetry.lock`. Any chance you can kick off tests again.

**Comment by samuelcolvin** [comment]
sorry, please can you kick off tests again.

**Comment by samuelcolvin** [comment]
thanks a lot, I really don't know what I'm doing with poetry.

**Comment by patrick91** [comment]
> thanks a lot, I really don't know what I'm doing with poetry.

same :D I usually delete and recreate the lock file when there's weird errors 😊

**Comment by samuelcolvin** [comment]
time for hatchling and pip-compile!

**Comment by samuelcolvin** [comment]
Looks like it's just CodeQL churning way, seems tests are passing, closing this.

Thanks so much for your help.

**Comment by patrick91** [comment]
no worries! thanks for checking if all works with Strawberry!

**Pull request closed without merging**
