### PR TITLE
Update pagination.md

### PR DESCRIPTION
**Pull request by kerenduchan**
Improve pagination documentation and fix bugs in the sample code.
I have tested the updated sample code.

### CODE REVIEW

**Comment by kerenduchan** [comment]
The sample code is available here: https://github.com/kerenduchan/strawberry-pagination

**Comment by patrick91** [comment]
Hi @kerenduchan apologies for this, I just merged an old PR that was updating the pagination guides!

Would be interested in taking a look at the new guide and update this PR based on that? I think you could also add a link to your repos, I'm sure it will be very valuable for readers 😊

**Comment by kerenduchan** [comment]
Hi @patrick91! I would be happy to take a look at the new guide and update this PR. Did you see my message on discord (ideas) regarding cursor vs offset pagination?

**Comment by kerenduchan** [comment]
I'm closing this PR and will resubmit a new one on top of the updated version of the documentation.

**Pull request closed without merging**
