### PR TITLE
fix enum handling of non-unique values or strawberry.enum_value

### PR DESCRIPTION
**Pull request by devkral**
We try to initialize an enum with the value of a value. This doesn't work (why it worked some time ago, I don't know).
This PR fixes the logic:
- first execute the checks of the underlying graphql enum
- if no error happened then return the value by using the proper enum access

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR
Strange: no issue was opened? The code must have been broken for some time.
It fails for me for some versions.

Edit: see comments or heading.

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Alexander for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by devkral** [comment]
there is some magic in use (at least with parse_literal). Please recheck my PR even the tests wok.

**Comment by patrick91** [comment]
hi @devkral, can you add some tests for the broken behaviour? 

I'm unsure on how this was broken, I've used enums successfully with strawberry :)

**Comment by devkral** [comment]
found the issue, the former code was partly correct:

enums allow the retrieval of values by wrapping them with enums.
This behavior works only correct if values are unique.
Also it fails if strawberry.enum_value is in use.

I modified the tests to demonstrate the issue.

**Comment by devkral** [comment]
a nice sideeffect: by don't searching the values it should also improve the performance for bigger enums

**Comment by devkral** [comment]
a nice sideeffect: it doesn't use the complicated code path of enums returning the value as a singleton. I think it will improve the speed at least a little bit.

**Comment by devkral** [comment]
found a second issue:
EnumValueDefinition should not appear as a value

**Comment by devkral** [comment]
sry, my test only works because of strawberry.enum_value. This is why the different keys with the same value can be differed. Actually you cannot differ keys with the same value.

the former code was correct, but the issue was at a different place: enums are not replaced

**Pull request closed without merging**
