### PR TITLE
update MaskErrors extension to use new extension api

### PR DESCRIPTION
**Pull request by N-Maas**
Seems this extension was missed when the new extension api was introduced.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Nikolai Maas for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by N-Maas** [comment]
Okay, should be added now :)

However, I want to note that it would help a lot if there was an explanation on how to do this. It took me a bit to figure out it's supposed to be a file in the top-level repository that is committed within the PR.

**Comment by patrick91** [comment]
@N-Maas it is written here: https://github.com/strawberry-graphql/strawberry/blob/main/CONTRIBUTING.md#releasemd-files and in the initial comment from the bot:

image

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Comment by N-Maas** [comment]
@patrick91  Yeah I saw that. But it was not clear to me what "include a RELEASE.md file" is supposed to mean, exactly. At least for me it was not intuitive that it should be part of the commits or where it should be placed.

It think it might help if the description is adjusted to "include a RELEASE.md file in the top-level directory as as separate commit" instead, and similarly for the bot.

**Pull request merged**
