### PR TITLE
Fix mypy compat with those without pydantic

### PR DESCRIPTION
**Pull request by thejaminator**
## Description

Pydantic import caused those who didnt install pydantic to not be able to use the mypy plugin

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
# Pre-release
:wave:

Releasing commit [50131e2983bd7b28b8b0d1b52bd280066be37a35] to PyPi as pre-release! :package:

**Review by patrick91 — APPROVED** [review]

**Pull request merged**
