### PR TITLE
Add Awaitable in resolver type

### LINKED ISSUE #2500: Additional type hints for strawberry.field - so that it can be used with async reolvers
If I use strawberry.field as explained in the documentation for async resolvers I get the following warning from pylance. 
```python
import asyncio
import strawberry


async def resolve_hello(root) -> str:
    await asyncio.sleep(1)

    return "Hello world"


@strawberry.type
class Query:
    hello: str = strawberry.field(resolver=resolve_hello)


schema = strawberry.Schema(Query)
``` 

```
(module) strawberry
Expression of type "StrawberryField" cannot be assigned to declared type "str"
  "StrawberryField" is incompatible with "str"   
Pylance[reportGeneralTypeIssues]
```

It would be nice if you could enhance the overloeaded `field` defitions in field.py for use with couroutines. 

Used Version: 0.155.2

### PR DESCRIPTION
**Pull request by patrick91**
## Description

This PR adds Awaitable inside our type for resolvers passed
to `strawberry.field` :)

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Closes #2500

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

This release updates the typing for the resolver argument in
`strawberry.field`i to support async resolvers.
This means that now you won't get any type
error from Pyright when using async resolver, like the following example:

```python
import strawberry


async def get_user_age() -> int:
    return 0


@strawberry.type
class User:
    name: str
    age: int = strawberry.field(resolver=get_user_age)
```


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @patrick91 for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by skilkis — APPROVED** [review]
Looks very good @patrick91 ! Good tests too

**Comment by Mark90** [comment]
Hello!

It seems that this fix for pyright has made mypy unhappy. I can reproduce with this extra testcase in `tests/mypy/test_fields.yml`

```

- case: test_field_with_async_resolver
  main: |
    import strawberry

    async def get_user_age() -> int:
        return 0


    @strawberry.type
    class User:
        name: str
        age: int = strawberry.field(resolver=get_user_age)
  out: |
```

This returns:

```
E   pytest_mypy_plugins.utils.TypecheckAssertionError: Output is not expected:
E   Actual:
E     main:10: error: Argument "resolver" to "field" has incompatible type "Callable[[], Coroutine[Any, Any, int]]"; expected "Union[StrawberryResolver[<nothing>], Callable[..., <nothing>], Callable[..., Awaitable[<nothing>]], staticmethod[<nothing>], classmethod[<nothing>]]"  [arg-type] (diff)
E   Expected:
E     (empty)
====================
```

When I revert the resolver type change in `strawberry/fields.py` then the test passes.

**Comment by patrick91** [comment]
@Mark90 sorry about that! I'll take a look at this today

**Comment by patrick91** [comment]
@Mark90 I've opened an issue on Mypy's side: https://github.com/python/mypy/issues/14669

If that doesn't get solved I'll try to find a work around 😊

**Comment by Mark90** [comment]
Thanks a lot for the quick action :)

**Pull request merged**
