### PR TITLE
Bumped the version of typing_extensions to 4.0.0

### PR DESCRIPTION
**Pull request by tienman**
## Description

This release bumps the version of typing_extensions to >= 4.0.0 to fix the error: "cannot import Self from typing_extensions".

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by patrick91 — APPROVED** [review]
@tienman sorry for the delay! Thanks a lot for doing this PR 😊

I've updated the code to include a release file (that's what we use to bump the version and update the changelog)

**Comment by patrick91** [comment]
failing tests seem to be a flake, will re-run them

**Comment by tienman** [comment]
@patrick91 Thanks for adding the release file.

**Comment by patrick91** [comment]
Looks like there's something wrong with the tests, I'll check them later today 😊 definitely unrelated to this PR

**Comment by patrick91** [comment]
@tienman sorry for the delay on this!

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
