### PR TITLE
fix a breaking internal error in mypy if using field() with positional arguments

### PR DESCRIPTION
**Pull request by cake-monotone**
fix a breaking internal error in mypy if using field() with positional arguments

## Description

- add handling logic for positional arguments in mypy plugin

more concretely, mypy raises a breaking error for the following code:

```python
import strawberry

def resolver() -> str:
    return 'Hello, World!'

@strawberry.type
class Example:
    successed: str = strawberry.field(resolver=resolver)
    failed: str = strawberry.field(resolver)  # makes mypy break
```

```python
../t.py:7: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.950
Traceback (most recent call last):
  File "mypy/semanal.py", line 5301, in accept
  File "mypy/nodes.py", line 1021, in accept
  File "mypy/semanal.py", line 1121, in visit_class_def
  File "mypy/semanal.py", line 1201, in analyze_class
  File "mypy/semanal.py", line 1210, in analyze_class_body_common
  File "mypy/semanal.py", line 1256, in apply_class_plugin_hooks
  File "/home/msc-elice/git-cloned/strawberry/strawberry/ext/mypy_plugin.py", line 809, in custom_dataclass_class_maker_callback
    transformer.transform()
  File "/home/msc-elice/git-cloned/strawberry/strawberry/ext/mypy_plugin.py", line 487, in transform
    attributes = self.collect_attributes()
  File "/home/msc-elice/git-cloned/strawberry/strawberry/ext/mypy_plugin.py", line 664, in collect_attributes
    has_field_call, field_args = _collect_field_args(stmt.rvalue)
  File "/home/msc-elice/git-cloned/strawberry/strawberry/ext/mypy_plugin.py", line 454, in _collect_field_args
    assert name is not None
AssertionError: 
../t.py:7: : note: use --pdb to drop into pd
```

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Thanks for adding the `RELEASE.md` file!



Here's a preview of the changelog:

---

This release fixes a breaking internal error in mypy plugin for the following case.
- using positional arguments to pass a resolver for `strawberry.field()` or `strawberry.mutation()`

```python
failed: str = strawberry.field(resolver)
successed: str = strawberry.field(resolver=resolver)
```

now mypy returns an error with `"field()" or "mutation()" only takes keyword arguments` message
rather than an internal error.


---
Here's the preview release card for twitter:




Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to cake-monotone for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Comment by cake-monotone** [comment]
I think the release type can be `minor`. it's enough 

If you want, I will change it.

**Review by patrick91 — APPROVED** [review]
Nice one! Thank you! 😊

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
