### PR TITLE
Always pass `info` to Field.get-result

### PR DESCRIPTION
**Pull request by la4de**
This pull request tries to fix regression caused by #1044.

This needs still more testing and changes to strawberry-django package as well. See https://github.com/strawberry-graphql/strawberry-graphql-django/tree/wip/fix-strawberry-regression.

### CODE REVIEW

**Comment by la4de** [comment]
@patrick91 , do these changes make sense? I'd like to hear your feedback before I continue?

**Comment by patrick91** [comment]
> @patrick91 , do these changes make sense? I'd like to hear your feedback before I continue?

Will check this tonight!

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Review by patrick91 — APPROVED** [review]
Yup, this makes sense to me!

**Pull request merged**
