### PR TITLE
change: parse query params to use parse_json

### PR DESCRIPTION
**Pull request by thearchitector**
## Description

Updated the base view generic to also use `parse_json` when loading parameters from the query string. It makes overriding easier / centralized to the `parse_json` and `encode_json` functions.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Elias Gabriel for the PR 👏

Get it here 👉 https://beta.strawberry.rocks/release/(next)
```

**Review by patrick91 — APPROVED** [review]
Makes sense! Thanks 😊

**Comment by patrick91** [comment]
@thearchitector  can you fix these two small lint issues?

```
strawberry/http/sync_base_view.py:160: error: Unused "type: ignore" comment  [unused-ignore]
strawberry/http/async_base_view.py:220: error: Unused "type: ignore" comment  [unused-ignore]
```

**Comment by thearchitector** [comment]
> @thearchitector can you fix these two small lint issues?
> 
> ```
> strawberry/http/sync_base_view.py:160: error: Unused "type: ignore" comment  [unused-ignore]
> strawberry/http/async_base_view.py:220: error: Unused "type: ignore" comment  [unused-ignore]
> ```

@patrick91 im not sure if im doing something wrong, but if i `poetry shell` and `mypy --config-file mypy.ini`, i get a lot more typing errors other than just those 2. mainly in `experimental/pydantic`, but a few in the mypy ext:

```
Warning: Unpack is already enabled by default
strawberry/experimental/pydantic/_compat.py:42: error: "type[BaseModel]" has no attribute "model_fields"  [attr-defined]
strawberry/experimental/pydantic/_compat.py:48: error: "FieldInfo" has no attribute "annotation"  [attr-defined]
strawberry/experimental/pydantic/_compat.py:49: error: "FieldInfo" has no attribute "annotation"  [attr-defined]
strawberry/experimental/pydantic/_compat.py:52: error: "FieldInfo" has no attribute "is_required"  [attr-defined]
strawberry/experimental/pydantic/_compat.py:68: error: Unused "type: ignore" comment  [unused-ignore]
strawberry/experimental/pydantic/_compat.py:73: error: Unused "type: ignore" comment  [unused-ignore]
strawberry/experimental/pydantic/_compat.py:78: error: Unused "type: ignore" comment  [unused-ignore]
strawberry/experimental/pydantic/_compat.py:85: error: Argument "required" to "CompatModelField" has incompatible type "bool | UndefinedType"; expected "bool"  [arg-type]
strawberry/ext/mypy_plugin.py:418: error: Unused "type: ignore" comment  [unused-ignore]
strawberry/ext/mypy_plugin.py:420: error: Unexpected keyword argument "api" for "deserialize" of "PydanticModelField"  [call-arg]
strawberry/ext/mypy_plugin.py:457: error: Unused "type: ignore" comment  [unused-ignore]
strawberry/ext/mypy_plugin.py:471: error: Unexpected keyword argument "current_info" for "to_argument" of "PydanticModelField"  [call-arg]
```

and on top of it, Pyright/Pylance seems to need `type: ignore` on those two lines in order suppress this one. Happy to ignore that error though if we want mypy to be the authority here.
```
Argument of type "str | Any | None" cannot be assigned to
parameter "variables" of type "Dict[str, Any] | None" in function "__init__"
```

**Review by patrick91 — APPROVED** [review]
Looks great! Thanks 😊

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
