### PR TITLE
Minor cleanup in documentation

### PR DESCRIPTION
**Pull request by garyd203**
Minor changes to documentation based on my read-through as a first-time user.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] ~I have added tests to cover my changes.~
- [ ] ~I have tested the changes and verified that they work and don't break anything (as well as I can manage).~

### CODE REVIEW

**Comment by garyd203** [comment]
Yes, i am still adding to it, so i will take it out of draft in a day or so

**Comment by patrick91** [comment]
@garyd203 great! I'll wait before merging it then 😊

**Comment by garyd203** [comment]
@patrick91 all finished, thanks!

**Review by estyxx — APPROVED** [review]
Thanks to contributing! Looks Good to me :)

**Review by patrick91 — APPROVED** [review]
Nice one! <3

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
