### PR TITLE
Docs: Ensure syntax highlighting is present (and consistent)

### PR DESCRIPTION
**Pull request by watfordkcf**
## Description

I noticed some code fences weren't being syntax highlighted, so I did a quick inventory and made sure they were present and consistent.

Question: is it worth standardizing the naked code fences with shell code to `bash` or `shell`? I noticed this inconsistency, but did not include those wider changes here.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Documentation

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by patrick91** [comment]
> Question: is it worth standardizing the naked code fences with shell code to bash or shell? I noticed this inconsistency, but did not include those wider changes here.

let's do that, let's go with shell since those commands are for people to run in the shell 😊

**Comment by watfordkcf** [comment]
I left out the changelog as I'm not quite sure if that was auto-generated or by hand.

**Review by patrick91 — APPROVED** [review]
Awesome! Thank you!

**Comment by patrick91** [comment]
> I left out the changelog as I'm not quite sure if that was auto-generated or by hand.

this is fine, they are autogenerated, and not used yet on the site 😊

**Pull request merged**
