### PR TITLE
refactor: move and merge resolver types to types.resolver

### PR DESCRIPTION
**Pull request by scratchmex**
I was struggling to understand where are the types for the resolvers and end up seeing a `type_resolvers.py` and `fields/resolver.py`. I tried to put the things in the most intuitively place.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Ivan Gonzalez for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```

**Review by BryceBeagle — COMMENTED** [review]
I think at some point the `._get_fields` logic might move to be located with the future `StrawberryObject` type (will serve to replace the monkeypatched `._type_definition` attribute we attach to `type`s right now). Determining the fields on a `type` isn't the responsibility of `StrawberryField`, it merely generates them. It will be the responsibility of the `StrawberryObject` constructor to do this.

I agree that this is a better place for this _right now_, however, so I think this is a good change for now.

Also, this is our long-term plan for the structure of internals. Maybe it can help with a discussion here: https://github.com/strawberry-graphql/strawberry/issues/849

**Comment by scratchmex** [comment]
Wow that internal restructuration is beautiful! Actually I was going through https://github.com/strawberry-graphql/strawberry/pull/489 when I found out this. I'm trying to help you to continue with that proposal.

**Comment by BryceBeagle** [comment]
I should probably add a comment to that PR saying that while the proposed changes are still planned, direct development on that branch has stagnated and the changes are going to come in piece-meal through other PRs. It became too much of an effort to keep that branch properly updated with changes on `main`. :grin:, so the diff is less-than-helpful.

**Comment by patrick91** [comment]
I'm going to close this as there's a lot of conflicts now 😊

**Pull request closed without merging**
